In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
df = pd.read_csv("../Dataset/Global_world.csv")

In [3]:
df

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175",...,45.80%,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368",6.423750,-66.589730
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",...,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",14.058324,108.277199
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",...,81.00%,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523",15.552727,48.516388
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",...,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",-13.133897,27.849332
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",...,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",-19.015438,29.154857

In [4]:
df.columns

Index(['Country', 'Density\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Armed Forces size', 'Birth Rate', 'Calling Code',
       'Capital/Major City', 'Co2-Emissions', 'CPI', 'CPI Change (%)',
       'Currency-Code', 'Fertility Rate', 'Forested Area (%)',
       'Gasoline Price', 'GDP', 'Gross primary education enrollment (%)',
       'Gross tertiary education enrollment (%)', 'Infant mortality',
       'Largest city', 'Life expectancy', 'Maternal mortality ratio',
       'Minimum wage', 'Official language', 'Out of pocket health expenditure',
       'Physicians per thousand', 'Population',
       'Population: Labor force participation (%)', 'Tax revenue (%)',
       'Total tax rate', 'Unemployment rate', 'Urban_population', 'Latitude',
       'Longitude'],
      dtype='object')

In [5]:
df.dtypes

Country                                       object
Density\n(P/Km2)                              object
Abbreviation                                  object
Agricultural Land( %)                         object
Land Area(Km2)                                object
Armed Forces size                             object
Birth Rate                                   float64
Calling Code                                 float64
Capital/Major City                            object
Co2-Emissions                                 object
CPI                                           object
CPI Change (%)                                object
Currency-Code                                 object
Fertility Rate                               float64
Forested Area (%)                             object
Gasoline Price                                object
GDP                                           object
Gross primary education enrollment (%)        object
Gross tertiary education enrollment (%)       object
Infant mortality                             float64
Largest city                                  object
Life expectancy                              float64
Maternal mortality ratio                     float64
Minimum wage                                  object
Official language                             object
Out of pocket health expenditure              object
Physicians per thousand                      float64
Population                                    object
Population: Labor force participation (%)     object
Tax revenue (%)                               object
Total tax rate                                object
Unemployment rate                             object
Urban_population                              object
Latitude                                     float64
Longitude                                    float64
dtype: object

In [6]:
df = df.rename(columns = {'Density\n(P/Km2)':'Density','Agricultural Land( %)':'Agricultural_Land','Land Area(Km2)':'Land_Area',
                          'Capital/Major City':'Capital_Major City','Co2-Emissions':'Co2_Emissions',
                          'Population: Labor force participation (%)':'Population_Labor_force_participation','Currency-Code':'Currency_Code '})

In [7]:
df

,Country,Density,Abbreviation,Agricultural_Land,Land_Area,Armed Forces size,Birth Rate,Calling Code,Capital_Major City,Co2_Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population_Labor_force_participation,Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175",...,45.80%,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368",6.423750,-66.589730
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",...,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",14.058324,108.277199
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",...,81.00%,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523",15.552727,48.516388
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",...,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",-13.133897,27.849332
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",...,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",-19.015438,29.154857

In [8]:
df.columns = df.columns.str.replace(" ","")
df

,Country,Density,Abbreviation,Agricultural_Land,Land_Area,ArmedForcessize,BirthRate,CallingCode,Capital_MajorCity,Co2_Emissions,...,Outofpockethealthexpenditure,Physiciansperthousand,Population,Population_Labor_force_participation,Taxrevenue(%),Totaltaxrate,Unemploymentrate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175",...,45.80%,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368",6.423750,-66.589730
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",...,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",14.058324,108.277199
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",...,81.00%,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523",15.552727,48.516388
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",...,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",-13.133897,27.849332
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",...,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",-19.015438,29.154857

In [9]:
df.columns = df.columns.str.replace('[()%]','',regex=True)
df

,Country,Density,Abbreviation,Agricultural_Land,Land_Area,ArmedForcessize,BirthRate,CallingCode,Capital_MajorCity,Co2_Emissions,...,Outofpockethealthexpenditure,Physiciansperthousand,Population,Population_Labor_force_participation,Taxrevenue,Totaltaxrate,Unemploymentrate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175",...,45.80%,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368",6.423750,-66.589730
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",...,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",14.058324,108.277199
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",...,81.00%,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523",15.552727,48.516388
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",...,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",-13.133897,27.849332
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",...,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",-19.015438,29.154857

In [10]:
df.columns

Index(['Country', 'Density', 'Abbreviation', 'Agricultural_Land', 'Land_Area',
       'ArmedForcessize', 'BirthRate', 'CallingCode', 'Capital_MajorCity',
       'Co2_Emissions', 'CPI', 'CPIChange', 'Currency_Code', 'FertilityRate',
       'ForestedArea', 'GasolinePrice', 'GDP',
       'Grossprimaryeducationenrollment', 'Grosstertiaryeducationenrollment',
       'Infantmortality', 'Largestcity', 'Lifeexpectancy',
       'Maternalmortalityratio', 'Minimumwage', 'Officiallanguage',
       'Outofpockethealthexpenditure', 'Physiciansperthousand', 'Population',
       'Population_Labor_force_participation', 'Taxrevenue', 'Totaltaxrate',
       'Unemploymentrate', 'Urban_population', 'Latitude', 'Longitude'],
      dtype='object')

In [11]:
df.isnull().sum()

Country                                  0
Density                                  0
Abbreviation                             7
Agricultural_Land                        7
Land_Area                                1
ArmedForcessize                         24
BirthRate                                6
CallingCode                              1
Capital_MajorCity                        3
Co2_Emissions                            7
CPI                                     17
CPIChange                               16
Currency_Code                           15
FertilityRate                            7
ForestedArea                             7
GasolinePrice                           20
GDP                                      2
Grossprimaryeducationenrollment          7
Grosstertiaryeducationenrollment        12
Infantmortality                          6
Largestcity                              6
Lifeexpectancy                           8
Maternalmortalityratio                  14
Minimumwage                             45
Officiallanguage                         5
Outofpockethealthexpenditure             7
Physiciansperthousand                    7
Population                               1
Population_Labor_force_participation    19
Taxrevenue                              26
Totaltaxrate                            12
Unemploymentrate                        19
Urban_population                         5
Latitude                                 1
Longitude                                1
dtype: int64

In [12]:
df.fillna(0)

,Country,Density,Abbreviation,Agricultural_Land,Land_Area,ArmedForcessize,BirthRate,CallingCode,Capital_MajorCity,Co2_Emissions,...,Outofpockethealthexpenditure,Physiciansperthousand,Population,Population_Labor_force_participation,Taxrevenue,Totaltaxrate,Unemploymentrate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,0,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",0,0,0,0,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175",...,45.80%,1.92,"28,515,829",59.70%,0,73.30%,8.80%,"25,162,368",6.423750,-66.589730
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",...,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",14.058324,108.277199
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",...,81.00%,0.31,"29,161,922",38.00%,0,26.60%,12.91%,"10,869,523",15.552727,48.516388
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",...,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",-13.133897,27.849332
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",...,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",-19.015438,29.154857

In [13]:
df.Country.unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'The Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Ivory Coast',
       'Cape Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Republic of the Congo', 'Costa Rica', 'Croatia',
       'Cuba', 'Cyprus', 'Czech Republic',
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
       'The Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada',
       'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
       'Vatican City', 'Honduras', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Republic of Ireland', 'Israel',
       'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya',
       'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon',
       'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania',
       'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
       'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius',
       'Mexico', 'Federated States of Micronesia', 'Moldova', 'Monaco',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia',
       'Norway', 'Oman', 'Pakistan', 'Palau',
       'Palestinian National Authority', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar',
       'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa',
       'San Marino', 'S�����������', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Korea',
       'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syria', 'Tajikistan', 'Tanzania', 'Thailand',
       'East Timor', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam',
       'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

In [14]:
df[df.Country=='S�����������']

,Country,Density,Abbreviation,Agricultural_Land,Land_Area,ArmedForcessize,BirthRate,CallingCode,Capital_MajorCity,Co2_Emissions,...,Outofpockethealthexpenditure,Physiciansperthousand,Population,Population_Labor_force_participation,Taxrevenue,Totaltaxrate,Unemploymentrate,Urban_population,Latitude,Longitude
150,S�����������,228,ST,50.70%,964,"1,000",31.54,239.0,S����,121,...,11.70%,0.05,"215,056",57.80%,14.60%,37.00%,13.37%,"158,277",NaN,NaN

In [15]:
df = df.drop(labels=150,axis=0)

In [16]:
df.Density.unique()

array(['60', '105', '18', '164', '26', '223', '17', '104', '3', '109',
       '123', '39', '2,239', '1,265', '668', '47', '383', '108', '20',
       '11', '64', '4', '25', '83', '76', '463', '138', '95', '56', '8',
       '13', '153', '46', '467', '16', '100', '73', '106', '131', '139',
       '40', '137', '43', '96', '225', '71', '103', '313', '50', '35',
       '31', '67', '115', '49', '119', '9', '239', '57', '240', '81',
       '331', '167', '53', '70', '414', '2,003', '89', '107', '464',
       '151', '52', '93', '72', '400', '206', '273', '347', '7', '94',
       '147', '34', '32', '30', '667', '238', '242', '48', '203', '99',
       '1,802', '1,380', '329', '5', '626', '66', '784', '26,337', '2',
       '541', '508', '55', '19', '226', '214', '15', '287', '847', '58',
       '368', '124', '111', '248', '84', '525', '205', '301', '284',
       '566', '87', '8,358', '114', '527', '341', '219', '68', '152',
       '110', '393', '229', '75', '118', '281', '36', '79', '314', '38'],
      dtype=object)

In [17]:
df.Density = df.Density.replace('[,]','',regex=True).astype('int64')

In [18]:
df.Abbreviation.unique()

array(['AF', 'AL', 'DZ', 'AD', 'AO', 'AG', 'AR', 'AM', 'AU', 'AT', 'AZ',
       'BS', 'BH', 'BD', 'BB', 'BY', 'BE', 'BZ', 'BJ', 'BT', 'BO', 'BA',
       'BW', 'BR', 'BN', 'BG', 'BF', 'BI', 'CI', 'CV', 'KH', 'CM', 'CA',
       'CF', 'TD', 'CL', 'CN', 'CO', 'KM', nan, 'CR', 'HR', 'CU', 'CY',
       'CZ', 'CD', 'DK', 'DJ', 'DM', 'DO', 'EC', 'EG', 'SV', 'GQ', 'ER',
       'EE', 'ET', 'FJ', 'FI', 'FR', 'GA', 'GM', 'GE', 'DE', 'GH', 'GR',
       'GD', 'GT', 'GN', 'GW', 'GY', 'HT', 'HN', 'HU', 'IS', 'IN', 'ID',
       'IR', 'IQ', 'IL', 'IT', 'JM', 'JP', 'JO', 'KZ', 'KE', 'KI', 'KW',
       'KG', 'LA', 'LV', 'LB', 'LS', 'LR', 'LY', 'LI', 'LT', 'LU', 'MG',
       'MW', 'MY', 'MV', 'ML', 'MT', 'MH', 'MR', 'MU', 'MX', 'FM', 'MD',
       'MC', 'MN', 'ME', 'MA', 'MZ', 'MM', 'NR', 'NP', 'NL', 'NZ', 'NI',
       'NE', 'NG', 'KP', 'NO', 'OM', 'PK', 'PW', 'PA', 'PG', 'PY', 'PE',
       'PH', 'PL', 'PT', 'QA', 'RO', 'RU', 'RW', 'KN', 'LC', 'VC', 'WS',
       'SM', 'SA', 'SN', 'RS', 'SC', 'SL', 'SG', 'SK', 'SI', 'SB', 'SO',
       'ZA', 'KR', 'SS', 'ES', 'LK', 'SD', 'SR', 'SE', 'CH', 'SY', 'TJ',
       'TZ', 'TH', 'TL', 'TG', 'TO', 'TT', 'TN', 'TR', 'TM', 'TV', 'UG',
       'UA', 'AE', 'GB', 'US', 'UY', 'UZ', 'VU', 'VE', 'VN', 'YE', 'ZM',
       'ZW'], dtype=object)

In [148]:
df.Agricultural_Land.unique()

array([58.1, 43.1, 17.4, 40. , 47.5, 20.5, 54.3, 58.9, 48.2, 32.4, 57.7,
        1.4, 11.1, 70.6, 23.3, 42. , 44.6,  7. , 33.3, 13.6, 34.8, 45.6,
        2.7, 46.3, 44.2, 79.2, 64.8, 19.6, 30.9, 20.6,  6.9,  8.2, 39.7,
       21.2, 56.2, 40.3, 71.5, 31.1, 34.5, 27.6, 59.9, 12.2, 45.2, 11.6,
       62. , 73.4, 48.7, 22.2,  3.8, 76.4, 10.1, 75.2, 23.1,  0. , 36.3,
        7.5, 52.4, 20. , 59.8, 47.7, 69. , 47.6, 23.5, 36. , 59. , 58. ,
        8.6, 66.8, 28.9, 58.4, 18.7, 60.4, 31.5, 28.2, 21.4, 64.5, 24.6,
       43.2, 41. , 12.3, 12. , 80.4, 48.5,  8.4, 55. , 10.3, 64.3, 77.6,
       28. ,  8.7, 32.2, 47.2, 53.7, 71.2, 61.4, 26.3, 33.8, 63.9, 38.5,
       42.4, 54.6, 31.4, 74.2, 19. , 68.5, 63.5, 19.5, 47.1, 28.7, 53.3,
       40.5, 42.1, 36.1, 77.7, 21.8,  4.6, 47.8, 10.9, 30.4,  2.6, 55.1,
       18.5, 41.7, 46.9, 39.5,  5.8, 58.8, 13.3, 25.6, 12.4, 16.7, 80.8,
       46.1, 39.3,  3.4, 54.7,  0.9, 39.2, 30.7,  3.9, 70.3, 79.8, 52.6,
       43.7,  0.6, 75.8, 34.1, 44.8, 43.3, 70.2, 45.8, 10.5, 49.8, 72. ,
       60. , 71.9, 71.7,  5.5, 44.4, 82.6, 62.9, 15.3, 24.5, 32.1, 41.9])

In [145]:
df.Agricultural_Land = df.Agricultural_Land.replace('[%]','',regex=True).astype('float64')

In [147]:
df.Agricultural_Land = df.Agricultural_Land.fillna(0)

In [154]:
df.Land_Area.unique()

array([  652230,    28748,  2381741,      468,  1246700,      443,
        2780400,    29743,  7741220,    83871,    86600,    13880,
            765,   148460,      430,   207600,    30528,    22966,
         112622,    38394,  1098581,    51197,   581730,     5765,
         110879,   274200,    27830,   322463,     4033,   181035,
         475440,  9984670,   622984,  1284000,   756096,  9596960,
        1138910,     2235,   342000,    51100,    56594,   110860,
           9251,    78867,  2344858,    43094,    23200,      751,
          48670,   283561,  1001450,    21041,    28051,   117600,
          45228,    17364,  1104300,    18274,   338145,   643801,
         267667,    11300,    69700,   357022,   238533,   131957,
            349,   108889,   245857,    36125,   214969,    27750,
              0,   112090,    93028,   103000,  3287263,  1904569,
        1648195,   438317,    70273,    20770,   301340,    10991,
         377944,    89342,  2724900,   580367,      811,    17818,
         199951,   236800,    64589,    10400,    30355,   111369,
        1759540,      160,    65300,     2586,   587041,   118484,
         329847,      298,  1240192,      316,      181,  1030700,
           2040,  1964375,      702,    33851,        2,  1564116,
          13812,   446550,   799380,   676578,   824292,       21,
         147181,    41543,   268838,   130370,  1267000,   923768,
         120538,    25713,   323802,   309500,   796095,      459,
          75420,   462840,   406752,  1285216,   300000,   312685,
          92212,    11586,   238391, 17098240,    26338,      261,
            616,      389,     2831,       61,  2149690,   196722,
          77474,      455,    71740,      716,    49035,    20273,
          28896,   637657,  1219090,    99720,   644329,   505370,
          65610,  1861484,   163820,   185180,   144100,   947300,
         513120,    14874,    56785,      747,     5128,   163610,
         783562,   488100,       26,   241038,   603550,    83600,
         243610,  9833517,   176215,   447400,    12189,   912050,
         331210,   527968,   752618,   390757])

In [153]:

df.Land_Area = df.Land_Area.fillna(0).astype('int64')

In [156]:
df.ArmedForcessize.unique()

array([ 323000,    9000,  317000,       0,  117000,  105000,   49000,
         58000,   21000,   82000,    1000,   19000,  221000,  155000,
         32000,    2000,   12000,    6000,   71000,   11000,    8000,
         31000,   27000,  191000,   24000,   72000,   35000,  122000,
       2695000,  481000,   10000,   18000,   76000,   16000,   23000,
        134000,   15000,   13000,   41000,  836000,   42000,  202000,
        138000,    4000,   25000,  307000,    7000,   26000,  180000,
        146000,   43000,    3000,   40000, 3031000,  676000,  563000,
        209000,  178000,  347000,  261000,  116000,   29000,  129000,
         80000,   34000,   22000,  136000,    5000,  336000,  246000,
        513000,  112000,  215000, 1469000,   47000,  936000,  158000,
        153000,   52000,  126000, 1454000,  252000,   81000,   20000,
        634000,  185000,  196000,  124000,  239000,   17000,   28000,
        455000,   48000,  512000,   46000,  297000,   63000,  148000,
       1359000,   68000,  343000,  522000,   51000])

In [155]:
df.ArmedForcessize = df.ArmedForcessize.replace('[,]','',regex=True).astype('int64')

In [23]:
df.ArmedForcessize = df.ArmedForcessize.fillna(0)
df.fillna(0)

,Country,Density,Abbreviation,Agricultural_Land,Land_Area,ArmedForcessize,BirthRate,CallingCode,Capital_MajorCity,Co2_Emissions,...,Outofpockethealthexpenditure,Physiciansperthousand,Population,Population_Labor_force_participation,Taxrevenue,Totaltaxrate,Unemploymentrate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,652230,"323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,28748,"9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,2381741,"317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,0,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",0,0,0,0,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,1246700,"117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,912050,"343,000",17.88,58.0,Caracas,"164,175",...,45.80%,1.92,"28,515,829",59.70%,0,73.30%,8.80%,"25,162,368",6.423750,-66.589730
191,Vietnam,314,VN,39.30%,331210,"522,000",16.75,84.0,Hanoi,"192,668",...,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",14.058324,108.277199
192,Yemen,56,YE,44.60%,527968,"40,000",30.45,967.0,Sanaa,"10,609",...,81.00%,0.31,"29,161,922",38.00%,0,26.60%,12.91%,"10,869,523",15.552727,48.516388
193,Zambia,25,ZM,32.10%,752618,"16,000",36.19,260.0,Lusaka,"5,141",...,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",-13.133897,27.849332
194,Zimbabwe,38,ZW,41.90%,390757,"51,000",30.68,263.0,Harare,"10,983",...,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",-19.015438,29.154857

In [24]:
df.BirthRate.unique()

array([32.49, 11.78, 24.28,  7.2 , 40.73, 15.33, 17.02, 13.99, 12.6 ,
        9.7 , 14.  , 13.97, 18.18, 10.65,  9.9 , 10.3 , 20.79, 36.22,
       17.26, 21.75,  8.11, 24.82, 13.92, 14.9 ,  8.9 , 37.93, 39.01,
       35.74, 19.49, 22.46, 35.39, 10.1 , 35.35, 42.17, 12.43, 10.9 ,
       14.88, 31.88, 32.86,  9.  , 10.17, 10.46, 10.7 , 41.18, 10.6 ,
       21.47, 12.  , 19.51, 19.72, 26.38, 18.25, 33.24, 30.3 ,   nan,
       32.34, 21.28,  8.6 , 11.3 , 31.61, 38.54, 13.47,  9.5 , 29.41,
        8.1 , 16.47, 24.56, 36.36, 35.13, 19.97, 24.35, 21.6 ,  9.6 ,
       17.86, 18.07, 18.78, 29.08, 12.5 , 20.8 ,  7.3 , 16.1 ,  7.4 ,
       21.98, 21.77, 28.75, 27.89, 13.94, 27.1 , 23.55, 10.  , 17.55,
       26.81, 33.04, 18.83, 32.66, 34.12, 16.75, 14.2 , 41.54,  9.2 ,
       29.03, 33.69, 10.2 , 17.6 , 22.82,  5.9 , 24.13, 11.73, 18.94,
       37.52, 28.64, 19.89, 11.98, 20.64, 46.08, 37.91, 13.89, 10.4 ,
       19.19, 28.25, 18.98, 27.07, 20.57, 17.95, 20.55,  8.5 ,  9.54,
       11.5 , 31.7 , 14.24, 24.38,  6.8 , 17.8 , 34.52, 17.1 , 33.41,
        8.8 ,  9.4 , 32.44, 41.75, 20.51,  6.4 , 35.01,  7.9 , 15.83,
       32.18, 18.54, 11.4 , 23.69, 30.76, 36.7 , 10.34, 29.42, 33.11,
       24.3 , 12.94, 17.56, 16.03, 23.83, 38.14,  8.7 , 10.33, 11.  ,
       11.6 , 13.86, 23.3 , 29.6 , 17.88, 30.45, 36.19, 30.68])

In [25]:
df.BirthRate = df.BirthRate.fillna(0)
df.fillna(0)

,Country,Density,Abbreviation,Agricultural_Land,Land_Area,ArmedForcessize,BirthRate,CallingCode,Capital_MajorCity,Co2_Emissions,...,Outofpockethealthexpenditure,Physiciansperthousand,Population,Population_Labor_force_participation,Taxrevenue,Totaltaxrate,Unemploymentrate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,652230,"323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,28748,"9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,2381741,"317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,0,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",0,0,0,0,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,1246700,"117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,912050,"343,000",17.88,58.0,Caracas,"164,175",...,45.80%,1.92,"28,515,829",59.70%,0,73.30%,8.80%,"25,162,368",6.423750,-66.589730
191,Vietnam,314,VN,39.30%,331210,"522,000",16.75,84.0,Hanoi,"192,668",...,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",14.058324,108.277199
192,Yemen,56,YE,44.60%,527968,"40,000",30.45,967.0,Sanaa,"10,609",...,81.00%,0.31,"29,161,922",38.00%,0,26.60%,12.91%,"10,869,523",15.552727,48.516388
193,Zambia,25,ZM,32.10%,752618,"16,000",36.19,260.0,Lusaka,"5,141",...,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",-13.133897,27.849332
194,Zimbabwe,38,ZW,41.90%,390757,"51,000",30.68,263.0,Harare,"10,983",...,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",-19.015438,29.154857

In [26]:
df.CallingCode.unique()

array([9.300e+01, 3.550e+02, 2.130e+02, 3.760e+02, 2.440e+02, 1.000e+00,
       5.400e+01, 3.740e+02, 6.100e+01, 4.300e+01, 9.940e+02, 9.730e+02,
       8.800e+02, 3.750e+02, 3.200e+01, 5.010e+02, 2.290e+02, 9.750e+02,
       5.910e+02, 3.870e+02, 2.670e+02, 5.500e+01, 6.730e+02, 3.590e+02,
       2.260e+02, 2.570e+02, 2.250e+02, 2.380e+02, 8.550e+02, 2.370e+02,
       2.360e+02, 2.350e+02, 5.600e+01, 8.600e+01, 5.700e+01, 2.690e+02,
       2.420e+02, 5.060e+02, 3.850e+02, 5.300e+01, 3.570e+02, 4.200e+02,
       2.430e+02, 4.500e+01, 2.530e+02, 5.930e+02, 2.000e+01, 5.030e+02,
       2.400e+02, 2.910e+02, 3.720e+02, 2.680e+02, 2.510e+02, 6.790e+02,
       3.580e+02, 3.300e+01, 2.410e+02, 2.200e+02, 9.950e+02, 4.900e+01,
       2.330e+02, 3.000e+01, 5.020e+02, 2.240e+02, 2.450e+02, 5.920e+02,
       5.090e+02, 3.790e+02, 5.040e+02, 3.600e+01, 3.540e+02, 9.100e+01,
       6.200e+01, 9.800e+01, 9.640e+02, 3.530e+02, 9.720e+02, 3.900e+01,
       1.876e+03, 8.100e+01, 9.620e+02, 7.000e+00, 2.540e+02, 6.860e+02,
       9.650e+02, 9.960e+02, 8.560e+02, 3.710e+02, 9.610e+02, 2.660e+02,
       2.310e+02, 2.180e+02, 4.230e+02, 3.700e+02, 3.520e+02, 2.610e+02,
       2.650e+02, 6.000e+01, 9.600e+02, 2.230e+02, 3.560e+02, 6.920e+02,
       2.220e+02, 2.300e+02, 5.200e+01, 6.910e+02, 3.730e+02, 3.770e+02,
       9.760e+02, 3.820e+02, 2.120e+02, 2.580e+02, 9.500e+01, 2.640e+02,
       6.740e+02, 9.770e+02, 3.100e+01, 6.400e+01, 5.050e+02, 2.270e+02,
       2.340e+02, 8.500e+02, 3.890e+02, 4.700e+01, 9.680e+02, 9.200e+01,
       6.800e+02,       nan, 5.070e+02, 6.750e+02, 5.950e+02, 5.100e+01,
       6.300e+01, 4.800e+01, 3.510e+02, 9.740e+02, 4.000e+01, 2.500e+02,
       6.850e+02, 3.780e+02, 9.660e+02, 2.210e+02, 3.810e+02, 2.480e+02,
       2.320e+02, 6.500e+01, 4.210e+02, 3.860e+02, 6.770e+02, 2.520e+02,
       2.700e+01, 8.200e+01, 2.110e+02, 3.400e+01, 9.400e+01, 2.490e+02,
       5.970e+02, 4.600e+01, 4.100e+01, 9.630e+02, 9.920e+02, 2.550e+02,
       6.600e+01, 6.700e+02, 2.280e+02, 6.760e+02, 2.160e+02, 9.000e+01,
       9.930e+02, 6.880e+02, 2.560e+02, 3.800e+02, 9.710e+02, 4.400e+01,
       5.980e+02, 9.980e+02, 6.780e+02, 5.800e+01, 8.400e+01, 9.670e+02,
       2.600e+02, 2.630e+02])

In [176]:
df = df.drop('CallingCode',axis=1)

In [177]:
df

,Country,Density,Abbreviation,Agricultural_Land,Land_Area,ArmedForcessize,BirthRate,Capital_MajorCity,Co2_Emissions,CPI,...,Outofpockethealthexpenditure,Physiciansperthousand,Population,Population_Labor_force_participation,Taxrevenue,Totaltaxrate,Unemploymentrate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.1,652230,323000,32.49,Kabul,8672,149.90,...,78.4,0.28,38041754,48.9,9.3,71.4,11.12,9797273,33.939110,67.709953
1,Albania,105,AL,43.1,28748,9000,11.78,Tirana,4536,119.05,...,56.9,1.20,2854191,55.7,18.6,36.6,12.33,1747593,41.153332,20.168331
2,Algeria,18,DZ,17.4,2381741,317000,24.28,Algiers,150006,151.36,...,28.1,1.72,43053054,41.2,37.2,66.1,11.70,31510100,28.033886,1.659626
3,Andorra,164,AD,40.0,468,0,7.20,Andorra la Vella,469,0.00,...,36.4,3.33,77142,0.0,0.0,0.0,0.00,67873,42.506285,1.521801
4,Angola,26,AO,47.5,1246700,117000,40.73,Luanda,34693,261.73,...,33.4,0.21,31825295,77.5,9.2,49.1,6.89,21061025,-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.5,912050,343000,17.88,Caracas,164175,2740.27,...,45.8,1.92,28515829,59.7,0.0,73.3,8.80,25162368,6.423750,-66.589730
191,Vietnam,314,VN,39.3,331210,522000,16.75,Hanoi,192668,163.52,...,43.5,0.82,96462106,77.4,19.1,37.6,2.01,35332140,14.058324,108.277199
192,Yemen,56,YE,44.6,527968,40000,30.45,Sanaa,10609,157.58,...,81.0,0.31,29161922,38.0,0.0,26.6,12.91,10869523,15.552727,48.516388
193,Zambia,25,ZM,32.1,752618,16000,36.19,Lusaka,5141,212.31,...,27.5,1.19,17861030,74.6,16.2,15.6,11.43,7871713,-13.133897,27.849332
194,Zimbabwe,38,ZW,41.9,390757,51000,30.68,Harare,10983,105.51,...,25.8,0.21,14645468,83.1,20.7,31.6,4.95,4717305,-19.015438,29.154857

In [28]:
df.Capital_MajorCity.unique()

array(['Kabul', 'Tirana', 'Algiers', 'Andorra la Vella', 'Luanda',
       "St. John's, Saint John", 'Buenos Aires', 'Yerevan', 'Canberra',
       'Vienna', 'Baku', 'Nassau, Bahamas', 'Manama', 'Dhaka',
       'Bridgetown', 'Minsk', 'City of Brussels', 'Belmopan',
       'Porto-Novo', 'Thimphu', 'Sucre', 'Sarajevo', 'Gaborone',
       'Bras���', 'Bandar Seri Begawan', 'Sofia', 'Ouagadougou',
       'Bujumbura', 'Yamoussoukro', 'Praia', 'Phnom Penh', 'Yaound�',
       'Ottawa', 'Bangui', "N'Djamena", 'Santiago', 'Beijing', 'Bogot�',
       'Moroni, Comoros', 'Brazzaville', 'San Jos������', 'Zagreb',
       'Havana', 'Nicosia', 'Prague', 'Kinshasa', 'Copenhagen',
       'Djibouti City', 'Roseau', 'Santo Domingo', 'Quito', 'Cairo',
       'San Salvador', 'Malabo', 'Asmara', 'Tallinn', 'Mbabane',
       'Addis Ababa', 'Suva', 'Helsinki', 'Paris', 'Libreville', 'Banjul',
       'Tbilisi', 'Berlin', 'Accra', 'Athens', "St. George's, Grenada",
       'Guatemala City', 'Conakry', 'Bissau', 'Georgetown, Guyana',
       'Port-au-Prince', 'Vatican City', 'Tegucigalpa', 'Budapest',
       'Reykjav��', 'New Delhi', 'Jakarta', 'Tehran', 'Baghdad', 'Dublin',
       'Jerusalem', 'Rome', 'Kingston, Jamaica', 'Tokyo', 'Amman',
       'Astana', 'Nairobi', 'South Tarawa', 'Kuwait City', 'Bishkek',
       'Vientiane', 'Riga', 'Beirut', 'Maseru', 'Monrovia', nan, 'Vaduz',
       'Vilnius', 'Luxembourg City', 'Antananarivo', 'Lilongwe',
       'Kuala Lumpur', 'Mal�', 'Bamako', 'Valletta', 'Majuro',
       'Nouakchott', 'Port Louis', 'Mexico City', 'Palikir', 'Chi����',
       'Monaco City', 'Ulaanbaatar', 'Podgorica', 'Rabat', 'Maputo',
       'Naypyidaw', 'Windhoek', 'Yaren District', 'Kathmandu',
       'Amsterdam', 'Wellington', 'Managua', 'Niamey', 'Abuja',
       'Pyongyang', 'Skopje', 'Oslo', 'Muscat', 'Islamabad', 'Ngerulmud',
       'Panama City', 'Port Moresby', 'Asunci��', 'Lima', 'Manila',
       'Warsaw', 'Lisbon', 'Doha', 'Bucharest', 'Moscow', 'Kigali',
       'Basseterre', 'Castries', 'Kingstown', 'Apia',
       'City of San Marino', 'Riyadh', 'Dakar', 'Belgrade',
       'Victoria, Seychelles', 'Freetown', 'Bratislava', 'Ljubljana',
       'Honiara', 'Mogadishu', 'Pretoria', 'Seoul', 'Juba', 'Madrid',
       'Colombo', 'Khartoum', 'Paramaribo', 'Stockholm', 'Bern',
       'Damascus', 'Dushanbe', 'Dodoma', 'Bangkok', 'Dili', 'Lom�',
       'Nuku����', 'Port of Spain', 'Tunis', 'Ankara', 'Ashgabat',
       'Funafuti', 'Kampala', 'Kyiv', 'Abu Dhabi', 'London',
       'Washington, D.C.', 'Montevideo', 'Tashkent', 'Port Vila',
       'Caracas', 'Hanoi', 'Sanaa', 'Lusaka', 'Harare'], dtype=object)

In [29]:
df.Capital_MajorCity = df.Capital_MajorCity.replace('�', '',regex=True)

In [159]:
df.Co2_Emissions.unique()

array([   8672,    4536,  150006,     469,   34693,     557,  201348,
          5156,  375908,   61448,   37620,    1786,   31694,   84246,
          1276,   58280,   96889,     568,    6476,    1261,   21606,
         21848,    6340,    7664,   41708,    3418,     495,    9674,
           543,    9919,    8291,  544894,     297,    1016,   85822,
       9893038,   97814,     202,    3282,    8023,   17488,   28284,
          6626,  102218,    2021,   31786,     620,     180,   25258,
         41155,  238560,    7169,    5655,     711,   16590,       0,
         14870,    2046,   45871,  303276,    5321,     532,   10128,
        727973,   16670,   62434,     268,   16777,    2996,     293,
          2384,    2978,    9813,   45537,    2065, 2407672,  563325,
        661710,  190061,   37711,   65166,  320411,    8225, 1135886,
         25108,  247207,   17910,      66,   98734,    9787,   17763,
          7004,   24796,    2512,    1386,   50564,      51,   12963,
          8988,    3905,    1298,  248289,    1445,    3179,    1342,
           143,    2739,    4349,  486406,    5115,   25368,    2017,
         61276,    7943,   25280,    4228,    9105,  170780,   34382,
          5592,  120369,   41023,   63457,  201150,     224,   10715,
          7536,    7407,   57414,  122287,  299037,   48742,  103259,
         69259, 1732027,    1115,     238,     414,     220,     246,
        563449,   10902,   45221,     605,    1093,   37535,   32424,
         12633,     169,     645,  476644,  620302,    1727,  244002,
         23362,   20000,    1738,   28830,    5310,   11973,  283763,
          3000,     128,   43868,   29937,  372725,   70630,      11,
          5680,  202250,  206324,  379025, 5006302,    6766,   91811,
           147,  164175,  192668,   10609,    5141,   10983])

In [158]:
df.Co2_Emissions = df.Co2_Emissions.fillna(0).astype('int64')

In [32]:
df.Co2_Emissions = df.Co2_Emissions.replace('[,]','',regex=True)

In [161]:
df.CPI.unique()

array([ 149.9 ,  119.05,  151.36,    0.  ,  261.73,  113.81,  232.75,
        129.18,  119.8 ,  118.06,  156.32,  116.22,  117.59,  179.68,
        134.09,  117.11,  105.68,  110.71,  167.18,  148.32,  104.9 ,
        149.75,   99.03,  114.42,  106.58,  182.11,  111.61,  110.5 ,
        127.63,  118.65,  116.76,  186.86,  117.7 ,  131.91,  125.08,
        140.95,  103.62,  124.74,  128.85,  109.82,  102.51,  116.48,
        133.85,  110.35,  120.25,  103.87,  135.5 ,  124.14,  288.57,
        111.23,  124.35,  122.14,  143.86,  132.3 ,  112.33,  110.05,
        122.19,  172.73,  133.61,  112.85,  268.36,  101.87,  107.43,
        142.92,  262.95,  111.65,  116.19,  179.29,  150.34,  121.64,
        129.  ,  180.44,  151.18,  550.93,  119.86,  108.15,  110.62,
        162.47,  105.48,  125.6 ,  182.75,  180.51,   99.55,  126.6 ,
        155.68,  135.87,  116.86,  130.02,  155.86,  223.13,  125.71,
        118.38,  115.09,  184.33,  418.34,  121.46,   99.7 ,  108.73,
        113.45,  135.02,  129.91,  141.54,  112.1 ,  166.2 ,  195.76,
        116.32,  111.07,  182.31,  168.18,  157.97,  188.73,  115.91,
        114.24,  162.74,  109.32,  267.51,  120.27,  113.53,  182.32,
        118.17,  122.07,  155.99,  143.82,  129.78,  129.61,  114.11,
        115.38,  123.78,  180.75,  151.09,  104.57,  110.13,  109.67,
        117.56,  110.63,  118.4 ,  109.25,  144.  ,  129.96,  234.16,
        114.41,  115.34,  111.05,  133.06,  158.93,  115.16, 4583.71,
        110.96,  155.53, 1344.19,  294.66,  143.2 ,  148.57,  187.43,
        113.27,  145.38,  113.3 ,  121.09,  141.75,  155.33,  234.44,
        173.87,  281.66,  114.52,  119.62,  117.24,  202.92,  117.13,
       2740.27,  163.52,  157.58,  212.31,  105.51])

In [34]:
df.CPI = df.CPI.fillna(0)

In [160]:
df.CPI = df.CPI.replace('[,]','',regex=True).astype('float64')

In [36]:

df.dtypes

Country                                  object
Density                                   int64
Abbreviation                             object
Agricultural_Land                        object
Land_Area                                object
ArmedForcessize                          object
BirthRate                               float64
CallingCode                             float64
Capital_MajorCity                        object
Co2_Emissions                            object
CPI                                     float64
CPIChange                                object
Currency_Code                            object
FertilityRate                           float64
ForestedArea                             object
GasolinePrice                            object
GDP                                      object
Grossprimaryeducationenrollment          object
Grosstertiaryeducationenrollment         object
Infantmortality                         float64
Largestcity                              object
Lifeexpectancy                          float64
Maternalmortalityratio                  float64
Minimumwage                              object
Officiallanguage                         object
Outofpockethealthexpenditure             object
Physiciansperthousand                   float64
Population                               object
Population_Labor_force_participation     object
Taxrevenue                               object
Totaltaxrate                             object
Unemploymentrate                         object
Urban_population                         object
Latitude                                float64
Longitude                               float64
dtype: object

In [37]:
df.Largestcity.unique()

array(['Kabul', 'Tirana', 'Algiers', 'Andorra la Vella', 'Luanda',
       "St. John's, Saint John", 'Buenos Aires', 'Yerevan', 'Sydney',
       'Vienna', 'Baku', 'Nassau, Bahamas', 'Riffa', 'Dhaka',
       'Bridgetown', 'Minsk', 'Brussels', 'Belize City', 'Cotonou',
       'Thimphu', 'Santa Cruz de la Sierra', 'Tuzla Canton', 'Gaborone',
       'S����', nan, 'Sofia', 'Ouagadougou', 'Bujumbura', 'Abidjan',
       'Praia', 'Phnom Penh', 'Douala', 'Toronto', 'Bangui', "N'Djamena",
       'Santiago', 'Shanghai', 'Bogot�', 'Moroni, Comoros', 'Brazzaville',
       'San Jos������', 'Zagreb', 'Havana', 'Statos�������', 'Prague',
       'Kinshasa', 'Copenhagen', 'Djibouti City', 'Roseau',
       'Santo Domingo', 'Quito', 'Cairo', 'San Salvador', 'Malabo',
       'Asmara', 'Tallinn', 'Mbabane', 'Addis Ababa', 'Suva', 'Helsinki',
       'Paris', 'Libreville', 'Serekunda', 'Tbilisi', 'Berlin', 'Accra',
       'Macedonia', "St. George's, Grenada", 'Guatemala City', 'Kankan',
       'Bissau', 'Georgetown, Guyana', 'Port-au-Prince', 'Tegucigalpa',
       'Budapest', 'Reykjav��', 'Kurebhar', 'Kalimantan', 'Tehran',
       'Baghdad', 'Connacht', 'Jerusalem', 'Rome', 'Kingston, Jamaica',
       'Tokyo', 'Amman', 'Almaty', 'Nairobi', 'South Tarawa',
       'Kuwait City', 'Bishkek', 'Vientiane', 'Riga', 'Tripoli, Lebanon',
       'Maseru', 'Monrovia', 'Schaan', 'Vilnius', 'Luxembourg City',
       'Antananarivo', 'Lilongwe', 'Johor Bahru', 'Mal�', 'Bamako',
       'Birkirkara', 'Majuro', 'Nouakchott', 'Port Louis', 'Mexico City',
       'Palikir', 'Chi����', 'Monaco City', 'Ulaanbaatar', 'Podgorica',
       'Casablanca', 'Maputo', 'Yangon', 'Windhoek', 'Kathmandu',
       'Amsterdam', 'Auckland', 'Managua', 'Niamey', 'Lagos', 'Pyongyang',
       'Skopje', 'Oslo', 'Seeb', 'Karachi', 'Koror', 'Panama City',
       'Port Moresby', 'Ciudad del Este', 'Lima', 'Manila', 'Warsaw',
       'Lisbon', 'Doha', 'Bucharest', 'Moscow', 'Kigali', 'Basseterre',
       'Castries', 'Calliaqua', 'Apia', 'City of San Marino', 'Riyadh',
       'Pikine', 'Belgrade', 'Victoria, Seychelles', 'Freetown',
       'Bratislava', 'Ljubljana', 'Honiara', 'Bosaso', 'Johannesburg',
       'Seoul', 'Juba', 'Madrid', 'Colombo', 'Omdurman', 'Paramaribo',
       'S�����', 'Z���', 'Damascus', 'Dushanbe', 'Dar es Salaam',
       'Bangkok', 'Dili', 'Lom�', 'Nuku����', 'Chaguanas', 'Tunis',
       'Istanbul', 'Ashgabat', 'Singapore', 'Buganda', 'Kyiv', 'Dubai',
       'London', 'New York City', 'Montevideo', 'Tashkent', 'Port Vila',
       'Caracas', 'Ho Chi Minh City', 'Sanaa', 'Lusaka', 'Harare'],
      dtype=object)

In [38]:
df[df.Largestcity=='S�����']

,Country,Density,Abbreviation,Agricultural_Land,Land_Area,ArmedForcessize,BirthRate,CallingCode,Capital_MajorCity,Co2_Emissions,...,Outofpockethealthexpenditure,Physiciansperthousand,Population,Population_Labor_force_participation,Taxrevenue,Totaltaxrate,Unemploymentrate,Urban_population,Latitude,Longitude
168,Sweden,25,SE,7.40%,450295,"30,000",11.4,46.0,Stockholm,43252,...,15.20%,3.98,"10,285,453",64.60%,27.90%,49.10%,6.48%,"9,021,165",60.128161,18.643501

In [39]:
df = df.drop(labels=168,axis=0)

In [40]:
df[df.Largestcity=='S����']

,Country,Density,Abbreviation,Agricultural_Land,Land_Area,ArmedForcessize,BirthRate,CallingCode,Capital_MajorCity,Co2_Emissions,...,Outofpockethealthexpenditure,Physiciansperthousand,Population,Population_Labor_force_participation,Taxrevenue,Totaltaxrate,Unemploymentrate,Urban_population,Latitude,Longitude
23,Brazil,25,BR,33.90%,8515770,"730,000",13.92,55.0,Bras,462299,...,28.30%,2.15,"212,559,417",63.90%,14.20%,65.10%,12.08%,"183,241,641",-14.235004,-51.92528

In [41]:
df = df.drop(labels=23,axis=0)

In [42]:
df[df.Largestcity == 'Z���']

,Country,Density,Abbreviation,Agricultural_Land,Land_Area,ArmedForcessize,BirthRate,CallingCode,Capital_MajorCity,Co2_Emissions,...,Outofpockethealthexpenditure,Physiciansperthousand,Population,Population_Labor_force_participation,Taxrevenue,Totaltaxrate,Unemploymentrate,Urban_population,Latitude,Longitude
169,Switzerland,219,CH,38.40%,41277,"21,000",10.0,41.0,Bern,34477,...,28.30%,4.3,"8,574,832",68.30%,10.10%,28.80%,4.58%,"6,332,428",46.818188,8.227512

In [43]:
df = df.drop(labels=169,axis=0)

In [44]:
df.Largestcity = df.Largestcity.replace('�', '',regex=True)

In [45]:
df.Outofpockethealthexpenditure.unique()

array(['78.40%', '56.90%', '28.10%', '36.40%', '33.40%', '24.30%',
       '17.60%', '81.60%', '19.60%', '17.90%', '78.60%', '27.80%',
       '25.10%', '71.80%', '45.20%', '34.50%', '22.70%', '40.50%',
       '19.80%', '25.90%', '28.60%', '5.30%', '6.00%', '47.70%', '36.10%',
       '19.10%', '36.00%', '23.20%', '59.40%', '69.70%', '14.60%',
       '39.60%', '56.40%', '32.20%', '32.40%', '18.30%', '74.80%',
       '43.80%', '21.50%', '15.20%', nan, '43.90%', '14.80%', '37.40%',
       '13.70%', '20.40%', '28.40%', '43.70%', '62.00%', '27.90%',
       '72.00%', '52.40%', '22.80%', '11.30%', '37.80%', '21.40%',
       '19.90%', '6.80%', '20.30%', '57.30%', '12.50%', '35.50%',
       '57.00%', '55.80%', '54.50%', '37.20%', '36.30%', '49.10%',
       '29.00%', '17.00%', '65.10%', '48.30%', '39.70%', '76.50%',
       '24.40%', '23.70%', '13.10%', '38.80%', '0.20%', '14.40%',
       '48.20%', '45.40%', '41.60%', '32.10%', '16.90%', '36.70%',
       '10.60%', '21.70%', '11.00%', '16.40%', '46.30%', '37.10%',
       '10.00%', '50.70%', '41.40%', '2.50%', '46.20%', '6.10%', '39.30%',
       '31.80%', '53.10%', '73.90%', '8.30%', '60.40%', '12.30%',
       '12.60%', '52.30%', '72.20%', '35.60%', '14.30%', '6.40%',
       '66.50%', '21.80%', '30.50%', '5.80%', '36.50%', '30.90%',
       '53.50%', '27.70%', '6.20%', '21.30%', '26.00%', '56.60%',
       '48.40%', '11.50%', '15.00%', '44.20%', '40.60%', '38.20%',
       '18.40%', '3.30%', '7.70%', '36.80%', '61.30%', '24.20%', '38.40%',
       '63.20%', '10.10%', '53.70%', '63.10%', '26.10%', '11.80%',
       '10.20%', '51.00%', '37.30%', '39.80%', '71.10%', '0.70%',
       '47.80%', '17.80%', '11.10%', '16.20%', '42.70%', '8.90%',
       '45.80%', '43.50%', '81.00%', '27.50%', '25.80%'], dtype=object)

In [46]:
df.Outofpockethealthexpenditure = df.Outofpockethealthexpenditure.fillna(0)

In [47]:
df['Outofpockethealthexpenditure'] = df['Outofpockethealthexpenditure'].str.replace('%', '', regex=True).astype('float64')

In [164]:
df.CPIChange.unique()

array([ 2.300e+00,  1.400e+00,  2.000e+00,        nan,  1.710e+01,
        1.200e+00,  5.350e+01,  1.600e+00,  1.500e+00,  2.600e+00,
        2.500e+00,  2.100e+00,  5.600e+00,  4.100e+00, -9.000e-01,
        2.700e+00,  1.800e+00,  6.000e-01,  2.800e+00, -4.000e-01,
        3.100e+00, -3.200e+00, -7.000e-01,  1.100e+00,  1.900e+00,
        3.710e+01, -1.000e+00,  2.900e+00,  3.500e+00, -4.300e+00,
        2.200e+00,  8.000e-01,  3.000e-01,  3.300e+00,  1.000e+00,
        9.200e+00,  1.000e-01,  1.580e+01,  7.100e+00,  4.900e+00,
        7.200e+00,  2.000e-01,  3.700e+00,  9.500e+00,  1.250e+01,
        4.400e+00,  3.000e+00,  7.700e+00,  3.990e+01,  4.000e-01,
        9.000e-01,  3.900e+00,  5.000e-01,  5.200e+00,  4.700e+00,
        2.360e+01,  1.700e+00,  9.400e+00,  7.000e-01, -1.700e+00,
        3.600e+00,  4.800e+00,  7.300e+00,  8.800e+00,  5.400e+00,
       -2.500e+00,  1.140e+01,  1.060e+01,  1.300e+00,  3.800e+00,
        4.500e+00,  3.400e+00, -1.200e+00,  1.480e+01,  1.879e+02,
        5.100e+01,  2.200e+01,  3.670e+01,  6.000e+00,  7.400e+00,
        6.700e+00,  1.520e+01,  7.900e+00, -1.900e+00,  7.500e+00,
        2.549e+02,  8.100e+00])

In [49]:
df.CPIChange = df.CPIChange.fillna(0)

In [163]:
df.CPIChange = df.CPIChange.str.replace('%', '', regex=True).astype('float64')

In [50]:
df.Currency_Code.unique()

array(['AFN', 'ALL', 'DZD', 'EUR', 'AOA', 'XCD', 'ARS', 'AMD', 'AUD',
       'AZN', nan, 'BHD', 'BDT', 'BBD', 'BYN', 'BZD', 'XOF', 'BOB', 'BAM',
       'BWP', 'BND', 'BGN', 'BIF', 'CVE', 'XAF', 'CAD', 'CLP', 'CNY',
       'COP', 'KMF', 'CRC', 'HRK', 'CUP', 'CZK', 'CDF', 'DKK', 'DJF',
       'DOP', 'USD', 'EGP', 'ERN', 'ETB', 'FJD', 'GMD', 'GEL', 'GHS',
       'GTQ', 'GNF', 'GYD', 'HTG', 'HNL', 'HUF', 'ISK', 'INR', 'IDR',
       'IRR', 'IQD', 'ILS', 'JMD', 'JOD', 'KZT', 'KES', 'KWD', 'KGS',
       'LAK', 'LBP', 'LYD', 'CHF', 'MGA', 'MWK', 'MYR', 'MRU', 'MUR',
       'MXN', 'MDL', 'MNT', 'MAD', 'MZN', 'MMK', 'NPR', 'NZD', 'NIO',
       'NGN', 'KPW', 'MKD', 'NOK', 'OMR', 'PKR', 'PGK', 'PYG', 'PEN',
       'PHP', 'PLN', 'QAR', 'RON', 'RUB', 'RWF', 'WST', 'SAR', 'RSD',
       'SCR', 'SLL', 'SGD', 'SBD', 'SOS', 'ZAR', 'KRW', 'SSP', 'LKR',
       'SDG', 'SRD', 'SYP', 'TJS', 'TZS', 'THB', 'TOP', 'TTD', 'TND',
       'TRY', 'TMT', 'UGX', 'UAH', 'AED', 'GBP', 'UYU', 'UZS', 'VUV',
       'VED', 'VND', 'YER', 'ZMW'], dtype=object)

In [178]:
df = df.drop('Currency_Code',axis=1)

In [179]:
df

,Country,Density,Abbreviation,Agricultural_Land,Land_Area,ArmedForcessize,BirthRate,Capital_MajorCity,Co2_Emissions,CPI,...,Outofpockethealthexpenditure,Physiciansperthousand,Population,Population_Labor_force_participation,Taxrevenue,Totaltaxrate,Unemploymentrate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.1,652230,323000,32.49,Kabul,8672,149.90,...,78.4,0.28,38041754,48.9,9.3,71.4,11.12,9797273,33.939110,67.709953
1,Albania,105,AL,43.1,28748,9000,11.78,Tirana,4536,119.05,...,56.9,1.20,2854191,55.7,18.6,36.6,12.33,1747593,41.153332,20.168331
2,Algeria,18,DZ,17.4,2381741,317000,24.28,Algiers,150006,151.36,...,28.1,1.72,43053054,41.2,37.2,66.1,11.70,31510100,28.033886,1.659626
3,Andorra,164,AD,40.0,468,0,7.20,Andorra la Vella,469,0.00,...,36.4,3.33,77142,0.0,0.0,0.0,0.00,67873,42.506285,1.521801
4,Angola,26,AO,47.5,1246700,117000,40.73,Luanda,34693,261.73,...,33.4,0.21,31825295,77.5,9.2,49.1,6.89,21061025,-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.5,912050,343000,17.88,Caracas,164175,2740.27,...,45.8,1.92,28515829,59.7,0.0,73.3,8.80,25162368,6.423750,-66.589730
191,Vietnam,314,VN,39.3,331210,522000,16.75,Hanoi,192668,163.52,...,43.5,0.82,96462106,77.4,19.1,37.6,2.01,35332140,14.058324,108.277199
192,Yemen,56,YE,44.6,527968,40000,30.45,Sanaa,10609,157.58,...,81.0,0.31,29161922,38.0,0.0,26.6,12.91,10869523,15.552727,48.516388
193,Zambia,25,ZM,32.1,752618,16000,36.19,Lusaka,5141,212.31,...,27.5,1.19,17861030,74.6,16.2,15.6,11.43,7871713,-13.133897,27.849332
194,Zimbabwe,38,ZW,41.9,390757,51000,30.68,Harare,10983,105.51,...,25.8,0.21,14645468,83.1,20.7,31.6,4.95,4717305,-19.015438,29.154857

In [52]:
df.FertilityRate.unique()

array([4.47, 1.62, 3.02, 1.27, 5.52, 1.99, 2.26, 1.76, 1.74, 1.47, 1.73,
       1.75, 2.04, 1.45, 2.31, 4.84, 1.98, 2.73, 2.87, 1.85, 1.56, 5.19,
       5.41, 4.65, 2.27, 2.5 , 4.57, 1.5 , 4.72, 5.75, 1.65, 1.69, 1.81,
       4.21, 4.43, 1.33, 5.92, 1.9 , 2.35, 2.43, 3.33, 4.51, 4.06, 1.59,
        nan, 4.25, 2.77, 1.41, 1.88, 3.97, 5.22, 2.06, 3.87, 1.35, 4.7 ,
       4.48, 2.46, 2.94, 1.54, 1.71, 2.22, 2.14, 3.67, 3.09, 1.29, 1.42,
       2.76, 2.84, 3.49, 3.57, 2.08, 3.3 , 2.67, 1.6 , 2.09, 3.14, 4.32,
       2.24, 1.44, 1.63, 1.37, 4.08, 2.  , 1.87, 5.88, 1.23, 4.05, 4.56,
       2.13, 3.05, 1.26, 2.9 , 2.42, 4.85, 2.15, 3.4 , 1.92, 2.4 , 6.91,
       5.39, 2.89, 3.51, 2.21, 3.56, 2.25, 2.58, 1.46, 1.38, 1.57, 4.04,
       2.11, 1.89, 3.88, 2.32, 4.63, 1.49, 2.41, 4.26, 1.14, 1.52, 4.4 ,
       6.07, 0.98, 2.2 , 4.41, 2.81, 3.59, 4.89, 1.53, 4.02, 2.07, 2.79,
       4.96, 1.3 , 1.68, 1.97, 3.78, 2.05, 3.79, 3.62])

In [53]:
df.FertilityRate = df.FertilityRate.fillna(0)

In [54]:
df.ForestedArea.unique()

array(['2.10%', '28.10%', '0.80%', '34.00%', '46.30%', '22.30%', '9.80%',
       '11.70%', '16.30%', '46.90%', '14.10%', '51.40%', '11.00%',
       '14.70%', '42.60%', '22.60%', '59.70%', '37.80%', '72.50%',
       '50.30%', '42.70%', '18.90%', '72.10%', '35.40%', '19.30%',
       '10.90%', '32.70%', '22.50%', '52.90%', '39.30%', '38.20%',
       '35.60%', '3.80%', '24.30%', '22.40%', '52.70%', '19.70%',
       '65.40%', '54.60%', '34.40%', '31.30%', '18.70%', '34.60%',
       '67.20%', '0.20%', '57.40%', '41.70%', '50.20%', '0.10%', '12.60%',
       '55.50%', '14.90%', '51.30%', nan, '12.50%', '55.90%', '73.10%',
       '31.20%', '90.00%', '48.40%', '40.60%', '41.20%', '31.70%',
       '50.00%', '25.80%', '69.80%', '83.90%', '3.50%', '40.00%',
       '22.90%', '0.50%', '23.80%', '49.90%', '6.60%', '1.90%', '7.70%',
       '31.80%', '30.90%', '68.50%', '1.10%', '1.20%', '7.80%', '15.00%',
       '0.40%', '3.30%', '82.10%', '54.00%', '13.40%', '1.60%', '43.10%',
       '34.80%', '35.70%', '21.40%', '33.20%', '67.60%', '70.20%',
       '19.00%', '33.90%', '91.90%', '8.00%', '61.50%', '48.00%',
       '43.60%', '8.30%', '25.40%', '11.20%', '38.60%', '25.90%', '0.90%',
       '7.20%', '40.70%', '0.00%', '87.60%', '61.90%', '74.10%', '37.70%',
       '57.70%', '27.80%', '30.10%', '49.80%', '42.30%', '69.20%',
       '60.40%', '42.80%', '31.10%', '88.40%', '23.10%', '40.40%',
       '62.00%', '77.90%', '10.00%', '7.60%', '63.40%', '36.90%',
       '32.90%', '8.10%', '98.30%', '2.70%', '3.00%', '51.60%', '32.20%',
       '45.40%', '3.10%', '46.00%', '6.80%', '15.40%', '8.80%', '33.30%',
       '9.70%', '16.70%', '4.60%', '13.10%', '10.70%', '7.50%', '36.10%',
       '48.10%', '1.00%', '65.20%', '35.50%'], dtype=object)

In [55]:
df.ForestedArea = df.ForestedArea.fillna(0)

In [56]:
df['ForestedArea'] = df['ForestedArea'].str.replace('%', '', regex=True).astype('float64')

In [57]:
df.GasolinePrice.unique()

array(['$0.70 ', '$1.36 ', '$0.28 ', '$1.51 ', '$0.97 ', '$0.99 ',
       '$1.10 ', '$0.77 ', '$0.93 ', '$1.20 ', '$0.56 ', '$0.92 ',
       '$0.43 ', '$1.12 ', '$1.81 ', '$0.60 ', '$1.43 ', '$1.13 ',
       '$0.72 ', '$0.98 ', '$0.71 ', '$1.05 ', '$0.37 ', '$1.11 ',
       '$1.21 ', '$1.02 ', '$0.90 ', '$1.03 ', '$0.81 ', '$1.41 ',
       '$0.78 ', '$0.96 ', '$0.68 ', nan, '$1.26 ', '$1.40 ', '$1.23 ',
       '$1.17 ', '$1.49 ', '$1.55 ', '$1.32 ', '$1.07 ', '$0.61 ',
       '$0.40 ', '$0.83 ', '$2.00 ', '$1.14 ', '$0.75 ', '$0.82 ',
       '$1.45 ', '$1.39 ', '$1.18 ', '$0.76 ', '$1.54 ', '$0.79 ',
       '$1.69 ', '$0.63 ', '$1.37 ', '$1.57 ', '$1.61 ', '$1.06 ',
       '$0.42 ', '$0.95 ', '$0.35 ', '$1.16 ', '$0.74 ', '$0.80 ',
       '$0.11 ', '$1.74 ', '$1.19 ', '$1.15 ', '$0.45 ', '$1.63 ',
       '$1.44 ', '$0.73 ', '$0.65 ', '$0.54 ', '$0.91 ', '$1.68 ',
       '$0.88 ', '$0.46 ', '$0.58 ', '$1.78 ', '$1.04 ', '$0.86 ',
       '$0.59 ', '$1.30 ', '$0.24 ', '$1.08 ', '$1.25 ', '$1.22 ',
       '$1.29 ', '$0.87 ', '$1.42 ', '$0.29 ', '$0.94 ', '$0.49 ',
       '$1.46 ', '$1.50 ', '$1.31 ', '$0.00 ', '$1.34 '], dtype=object)

In [58]:
df.GasolinePrice = df.GasolinePrice.replace('[$]','',regex=True).astype('float64')

In [59]:
df.GasolinePrice = df.GasolinePrice.fillna(0)

In [82]:
df.GDP.unique()

array([   19101353833,    15278077447,   169988236398,     3154057987,
          94635415870,     1727759259,   449663446954,    13672802158,
        1392680589329,   446314739528,    39207000000,    12827000000,
          38574069149,   302571254131,     5209000000,    63080457023,
         529606710418,     1879613600,    14390709095,     2446674101,
          40895322865,    20047848435,    18340510789,    13469422941,
          86000000000,    15745810235,     3012334882,    58792205642,
           1981845741,    27089389787,    38760467033,  1736425629520,
           2220307369,    11314951343,   282318159745, 19910000000000,
         323802808108,     1185728677,    10820591131,    61773944174,
          60415553039,   100023000000,    24564647935,   246489245495,
          47319624204,   348078018464,     3318716359,      596033333,
          88941298258,   107435665000,   303175127598,    27022640000,
          11026774945,     2065001626,    31386949981,     3791304348,
          96107662398,     5535548972,   268761201365,  2715518274227,
          16657960228,     1763819048,    17743195770,  3845630030824,
          66983634224,   209852761469,     1228170370,    76710385880,
          13590281809,     1340389411,     4280443645,     8498981821,
                    0,    25095395475,   160967157504,    24188035739,
        2611000000000,  1119190780753,   445345282123,   234094042939,
         388698711348,   395098666122,  2001244392042,    16458071068,
        5081769542380,    43743661972,   180161741180,    95503088538,
            194647202,   134761198946,     8454619608,    18173839128,
          34117202555,    53367042272,     2460072444,     3070518100,
          52076250948,     6552858739,    54219315600,    71104919108,
          14083906357,     7666704427,   364701517788,     5729248472,
          17510141171,    14786156563,      221278000,     7593752450,
          14180444557,  1258286717125,      401932279,    11955435457,
           7184844193,    13852850259,     5494736901,   118725279596,
          14934159926,    76085852617,    12366527719,      133000000,
          30641380604,   909070395161,   206928765544,    12520915291,
          12928145120,   448120428859,    32100000000,    10220781069,
         403336363636,    76983094928,   304400000000,      283994900,
          66800800000,    24969611435,    38145288940,   226848050820,
         376795508680,   592164400688,   237686075635,   183466208791,
         250077444017,  1699876578871,    10122472590,     1050992593,
           2122450630,      825385185,      850655017,     1637931034,
         792966838162,    23578084052,    51409167351,     1698843063,
           3941474311,   372062527489,   105422304976,    53742159517,
           1425074226,     4720727278,   351431649241,  2029000000000,
          11997800751,  1394116310769,    84008783756,    18902284476,
           3985250737,    40405006007,     8116626794,    63177068175,
         543649976166,     1673540300,     5459979417,      450353314,
          24100202834,    38797709924,   754411708203,    40761142857,
             47271463,    34387229486,   153781069118,   421142267938,
        2827113184696, 21427700000000,    56045912952,    57921286440,
            917058851,   482359318768,   261921244843,    26914402224,
          23064722446,    21440758800])

In [81]:
df['GDP'] = df['GDP'].str.replace(',', '', regex=True)

AttributeError: Can only use .str accessor with string values!

In [80]:
df.GDP = df.GDP.fillna(0).astype('int64')

In [78]:
df.GDP = df.GDP.str.replace('[$]','', regex=True)

In [169]:
df.Grossprimaryeducationenrollment.unique()

array([104. , 107. , 109.9, 106.4, 113.5, 105. , 109.7,  92.7, 100.3,
       103.1,  99.7,  81.4,  99.4, 116.5, 100.5, 103.9, 111.7, 122. ,
       100.1,  98.2,   0. , 103.2,  89.3,  96.1, 121.4,  99.8, 107.4,
       103.4, 100.9, 102. ,  86.8, 101.4, 100.2, 114.5,  99.5, 106.6,
       113.3,  96.5, 101.9,  99.3, 100.7, 108. , 101.3,  75.3, 114.7,
       105.7, 103.3, 106.3,  94.8,  61.8,  68.4,  97.2, 101. , 102.5,
       139.9,  98. ,  98.6, 104.8,  99.6, 106.9,  91.5, 118.7,  97.8,
       113.6, 100.8, 100.4, 113. , 110.7, 108.7, 104.9,  91. ,  98.8,
        81.5, 104.4,  92.4, 107.6, 102.4,  95.1, 120.9,  85.1, 109. ,
       104.7, 102.3, 142.5, 105.3,  97.1,  75.6,  84.7,  99.9, 101.1,
       105.8,  90.6, 100. , 113.9, 112.6, 112.3, 124.2, 142.1, 104.2,
       120.6,  74.7, 112.8,  94.3,  94.4, 108.5, 107.5, 106.2, 103.8,
        85.2, 102.6, 133. , 113.4, 110.5, 108.1,  81. , 100.6,  98.7,
        23.4,  98.1,  73. , 102.7,  76.8, 108.8,  81.7,  94.2, 115.3,
       123.8, 116.3, 115.4,  93.2,  88.4,  86. ,  99. , 108.4, 101.2,
       101.8, 109.3, 110.6,  93.6])

In [168]:
df.Grossprimaryeducationenrollment = df.Grossprimaryeducationenrollment.fillna(0)

In [166]:
df.Grossprimaryeducationenrollment = df.Grossprimaryeducationenrollment.str.replace('%', '', regex=True).astype('float64')

In [174]:
df.Grosstertiaryeducationenrollment.unique()

array([  9.7,  55. ,  51.4,   0. ,   9.3,  24.8,  90. ,  54.6, 113.1,
        85.1,  27.7,  15.1,  50.5,  20.6,  65.4,  87.4,  79.7,  24.7,
        12.3,  15.6,  23.3,  24.9,  31.4,  71. ,   6.5,   6.1,  23.6,
        13.7,  12.8,  68.9,   3. ,   3.3,  88.5,  50.6,  55.3,   9. ,
        12.7,  55.2,  67.9,  41.4,  75.9,  64.1,   6.6,  80.6,   5.3,
         7.2,  59.9,  44.9,  35.2,  29.4,   1.9,   3.4,  69.6,   8.1,
        16.1,  88.2,  65.6,   8.3,   2.7,  63.9,  70.2,  15.7, 136.6,
       104.6,  21.8,  11.6,   2.6,   1.1,  26.2,  48.5,  71.8,  28.1,
        36.3,  68.1,  16.2,  77.8,  63.4,  61.9,  27.1,  63.2,  34.4,
        61.7,  11.5,  54.4,  41.3,  15. ,  88.1,  26.3,  10.2,  11.9,
        60.5,  35.6,  72.4,  19.2,   5.4,   0.8,  45.1,  31.2,   4.5,
        54.3,  23.7,   5. ,  40.6,  40.2,  14.1,  39.8,  56.1,  35.9,
         7.3,  18.8,  22.9,  12.4,  85. ,  82. ,  17.4,   4.4,  27. ,
        38. ,  54.7,  47.8,   1.8,  34.6,  70.7,  35.5,  67.8,  17.9,
        49.4,  81.9,   6.7,  86.7,   7.6,  42.5,  68. ,  67.2,  17.1,
         2. ,  84.8,  46.6,  78.6,   2.5,  22.4,  94.3,  88.9,  19.6,
        16.9,  12.6,  40.1,  31.3,   4. ,  49.3,  17.8,  14.5,   6.4,
        12. ,  31.7,  23.9,   8. ,   4.8,  82.7,  36.8,  60. ,  63.1,
        10.1,   4.7,  79.3,  28.5,   4.1,  10. ])

In [173]:
df.Grosstertiaryeducationenrollment = df.Grosstertiaryeducationenrollment.fillna(0)

In [171]:
df.Grosstertiaryeducationenrollment = df.Grosstertiaryeducationenrollment.str.replace('%', '', regex=True).astype('float64')

In [63]:
df.Lifeexpectancy.unique()

array([64.5, 78.5, 76.7,  nan, 60.8, 76.9, 76.5, 74.9, 82.7, 81.6, 72.9,
       73.8, 77.2, 72.3, 79.1, 74.2, 74.5, 61.5, 71.5, 71.2, 77.3, 69.3,
       75.7, 61.2, 57.4, 72.8, 69.6, 58.9, 81.9, 52.8, 54. , 80. , 77. ,
       77.1, 64.1, 64.3, 80.1, 78.1, 78.7, 80.8, 79. , 60.4, 81. , 66.6,
       76.6, 73.9, 76.8, 71.8, 73.1, 58.4, 65.9, 78.2, 66.2, 67.3, 81.7,
       82.5, 61.7, 73.6, 80.9, 63.8, 81.3, 72.4, 74.1, 58. , 69.8, 63.7,
       75.1, 75.8, 69.4, 70.5, 82.3, 82.8, 82.9, 74.4, 84.2, 73.2, 66.3,
       68.1, 75.4, 71.4, 67.6, 74.7, 78.9, 53.7, 72.7, 83. , 82.1, 66.7,
       76. , 78.6, 65.2, 64.7, 75. , 67.8, 69.7, 60.2, 66.9, 63.4, 81.8,
       74.3, 62. , 54.3, 72.1, 77.6, 67.1, 69.1, 78.3, 71.1, 68.7, 71.3,
       76.1, 85.4, 67.7, 75.5, 83.1, 57.1, 63.9, 82.6, 57.6, 83.3, 65.1,
       71.6, 70.9, 65. , 70.8, 73.4, 77.4, 63. , 77.8, 70.3, 75.3, 66.1,
       63.5])

In [64]:
df.Lifeexpectancy = df.Lifeexpectancy.fillna(0)

In [65]:
df.Infantmortality.unique()

array([47.9,  7.8, 20.1,  2.7, 51.6,  5. ,  8.8, 11. ,  3.1,  2.9, 19.2,
        8.3,  6.1, 25.1, 11.3,  2.6, 11.2, 60.5, 24.8, 21.8, 30. ,  9.8,
        5.9, 49. , 41. , 59.4, 16.7, 24. , 50.6,  4.3, 84.5, 71.4,  6.2,
        7.4, 12.2, 51.3, 36.2,  7.6,  4. ,  3.7,  1.9, 68.2,  3.6, 49.8,
       32.9, 24.1, 18.1, 11.8, 62.6, 31.3,  2.1,  nan, 39.1, 21.6,  1.4,
        3.4, 32.7, 39. ,  8.7, 34.9, 13.7, 22.1, 64.9, 54. , 49.5, 15.1,
        1.5, 29.9, 21.1, 12.4, 22.5,  3. ,  1.8, 13.9, 30.6, 41.2,  6.7,
       16.9, 37.6,  3.3,  6.4, 65.7, 53.5, 10.2, 38.2, 35.3, 62. , 27.4,
       51.5, 13.6, 25.6, 14. ,  2.3, 36.8, 29. , 26.7,  4.7, 15.7, 48. ,
       75.7, 57.2, 16.6, 13.1, 38. , 17.2, 11.1,  3.8,  5.8, 27. , 14.9,
       14.8,  1.7,  6. , 31.8,  4.8, 78.5,  4.6, 17.1, 76.6, 28.5, 63.7,
        2.5, 42.1, 30.4, 39.3, 47.4, 13.4, 16.4, 14.6,  9.1, 20.6, 33.8,
        7.5,  6.5,  5.6, 19.1, 22.3, 21.4, 16.5, 42.9, 40.4, 33.9])

In [66]:
df.Infantmortality = df.Infantmortality.fillna(0)

In [67]:
df.Maternalmortalityratio.unique()

array([ 638.,   15.,  112.,   nan,  241.,   42.,   39.,   26.,    6.,
          5.,   70.,   14.,  173.,   27.,    2.,   36.,  397.,  183.,
        155.,   10.,  144.,   31.,  320.,  548.,  617.,   58.,  160.,
        529.,  829., 1140.,   13.,   29.,   83.,  273.,  378.,    8.,
          3.,  473.,    4.,  248.,   95.,   59.,   37.,   46.,  301.,
        480.,    9.,  401.,   34.,  252.,  597.,   25.,    7.,  308.,
        576.,  667.,  169.,   65.,   12.,  145.,  177.,   16.,   79.,
         80.,  342.,   92.,   60.,  185.,   19.,  544.,  661.,   72.,
        335.,  349.,   53.,  562.,  766.,   61.,   33.,   88.,   45.,
        289.,  250.,  195.,  186.,   98.,  509.,  917.,   89.,  140.,
         52.,  129.,  121.,   17.,  117.,   68.,   43.,  315., 1120.,
        104.,  119.,   11., 1150.,  295.,  120.,  524.,  142.,  396.,
         67.,  375.,  125.,  164.,  213.,  458.])

In [68]:
df.Maternalmortalityratio = df.Maternalmortalityratio.fillna(0)

In [86]:
df.Minimumwage.unique()

array([4.300e-01, 1.120e+00, 9.500e-01, 6.630e+00, 7.100e-01, 3.040e+00,
       3.350e+00, 6.600e-01, 1.359e+01, 0.000e+00, 4.700e-01, 5.250e+00,
       5.100e-01, 3.130e+00, 1.490e+00, 1.031e+01, 1.650e+00, 3.900e-01,
       3.200e-01, 1.360e+00, 1.040e+00, 2.900e-01, 1.570e+00, 3.400e-01,
       3.600e-01, 6.800e-01, 3.500e-01, 9.510e+00, 3.700e-01, 6.000e-01,
       2.000e+00, 8.700e-01, 1.230e+00, 8.800e-01, 1.840e+00, 2.920e+00,
       5.000e-02, 3.000e+00, 1.800e-01, 1.480e+00, 4.000e-01, 2.460e+00,
       5.000e-01, 1.050e+00, 3.140e+00, 1.280e+00, 1.116e+01, 1.460e+00,
       1.300e-01, 9.990e+00, 2.700e-01, 4.460e+00, 1.600e+00, 1.600e-01,
       9.800e-01, 2.500e-01, 1.010e+00, 2.620e+00, 3.000e-01, 4.800e-01,
       1.580e+00, 1.240e+00, 1.079e+01, 7.580e+00, 1.330e+00, 6.770e+00,
       4.100e-01, 9.000e-02, 8.300e-01, 2.800e+00, 2.150e+00, 1.700e-01,
       1.880e+00, 2.410e+00, 1.305e+01, 2.100e-01, 1.200e-01, 9.300e-01,
       2.300e-01, 5.070e+00, 5.300e-01, 3.800e-01, 4.900e-01, 3.100e-01,
       1.172e+01, 6.500e-01, 1.029e+01, 1.149e+01, 5.400e-01, 4.330e+00,
       6.900e-01, 1.530e+00, 1.160e+00, 1.550e+00, 2.930e+00, 3.780e+00,
       2.250e+00, 3.330e+00, 7.800e-01, 3.850e+00, 5.700e-01, 3.110e+00,
       6.490e+00, 5.600e+00, 1.020e+00, 1.060e+00, 3.450e+00, 1.000e-02,
       8.400e-01, 1.013e+01, 7.250e+00, 1.660e+00, 2.400e-01, 1.560e+00,
       7.300e-01])

In [83]:
df.Minimumwage = df.Minimumwage.str.replace('[$]', '', regex=True).astype('float64')

In [85]:
df.Minimumwage = df.Minimumwage.fillna(0)

In [89]:
df.Officiallanguage.unique()

array(['Pashto', 'Albanian', 'Arabic', 'Catalan', 'Portuguese', 'English',
       'Spanish', 'Armenian', 0, 'German', 'Azerbaijani language',
       'Bengali', 'Russian', 'French', 'Dzongkha', 'Bosnian', 'Malay',
       'Bulgarian', 'Kirundi', 'Khmer language', 'Standard Chinese',
       'Croatian', 'Greek', 'Czech', 'Danish', 'Modern Standard Arabic',
       'Tigrinya', 'Estonian', 'Amharic', 'Fiji Hindi', 'Swedish',
       'Georgian', 'Italian', 'Hungarian', 'Icelandic', 'Hindi',
       'Indonesian', 'Persian', 'Irish', 'Hebrew', 'Jamaican English',
       'Swahili', 'Lao', 'Latvian', 'Lithuanian', 'Luxembourgish',
       'Malaysian language', 'Divehi', 'Maltese', 'Marshallese',
       'Romanian', 'Mongolian', 'Montenegrin language', 'Burmese',
       'Nepali', 'Dutch', 'Korean', 'Macedonian', 'Norwegian', 'Urdu',
       'Tok Pisin', 'Polish', 'Samoan', 'Serbian', 'Slovak',
       'Slovene language', 'Afrikaans', 'Tamil', 'Thai',
       'Tongan Language', 'Turkish', 'Turkmen', 'Tuvaluan Language',
       'Ukrainian', 'Uzbek', 'Vietnamese', 'Shona'], dtype=object)

In [88]:
df.Officiallanguage = df.Officiallanguage.fillna(0)

In [92]:
df.Physiciansperthousand.unique()

array([0.28, 1.2 , 1.72, 3.33, 0.21, 2.76, 3.96, 4.4 , 3.68, 5.17, 3.45,
       1.94, 0.93, 0.58, 2.48, 5.19, 3.07, 1.12, 0.08, 0.42, 1.59, 2.16,
       0.37, 1.61, 4.03, 0.1 , 0.23, 0.77, 0.17, 0.09, 2.61, 0.06, 0.04,
       2.59, 1.98, 2.18, 0.27, 0.12, 2.89, 3.  , 8.42, 1.95, 4.12, 0.07,
       4.01, 0.22, 1.08, 1.56, 2.04, 0.45, 1.57, 0.4 , 4.48, 0.  , 0.84,
       3.81, 3.27, 0.68, 7.12, 4.25, 0.14, 5.48, 1.41, 0.35, 0.13, 0.8 ,
       0.31, 3.41, 4.08, 0.86, 0.43, 1.58, 0.71, 3.31, 4.62, 3.98, 1.31,
       2.41, 2.32, 3.25, 0.16, 0.2 , 2.58, 1.88, 3.19, 2.1 , 2.09, 6.35,
       3.01, 0.18, 1.51, 4.56, 2.86, 0.19, 2.53, 2.38, 3.21, 6.56, 0.73,
       0.75, 3.61, 3.59, 0.98, 0.38, 3.67, 2.92, 2.  , 1.18, 1.35, 1.27,
       0.6 , 5.12, 2.49, 2.98, 2.52, 0.64, 0.66, 0.34, 6.11, 3.11, 0.95,
       0.03, 2.29, 3.42, 3.09, 0.02, 0.91, 2.36, 3.87, 1.  , 0.26, 1.21,
       1.22, 1.7 , 0.01, 0.81, 0.72, 0.52, 4.17, 1.3 , 1.85, 2.22, 0.92,
       2.99, 2.81, 5.05, 2.37, 1.92, 0.82, 1.19])

In [91]:
df.Physiciansperthousand = df.Physiciansperthousand.fillna(0)

In [107]:
df.Population.unique()

array([  38041754,    2854191,   43053054,      77142,   31825295,
            97118,   44938712,    2957731,   25766605,    8877067,
         10023318,     389482,    1501635,  167310838,     287025,
          9466856,   11484055,     390353,   11801151,     727145,
         11513100,    3301000,    2346179,     433285,    6975761,
         20321378,   11530580,   25716544,     483628,   16486542,
         25876380,   36991981,    4745185,   15946876,   18952038,
       1397715000,   50339443,     850886,    5380508,    5047561,
          4067500,   11333483,    1198575,   10669709,   86790567,
          5818553,     973560,      71808,   10738958,   17373662,
        100388073,    6453553,    1355986,    6333135,    1331824,
          1093238,  112078730,     889953,    5520314,   67059887,
          2172579,    2347706,    3720382,   83132799,   30792608,
         10716322,     112003,   16604026,   12771246,    1920922,
           782766,   11263077,        836,    9746117,    9769949,
           361313, 1366417754,  270203917,   82913906,   39309783,
          5007069,    9053300,   60297396,    2948279,  126226568,
         10101694,   18513930,   52573973,     117606,    4207083,
          6456900,    7169455,    1912789,    6855713,    2125268,
          4937374,    6777452,      38019,    2786844,     645397,
         26969307,   18628747,   32447385,     530953,   19658031,
           502653,      58791,    4525696,    1265711,  126014024,
           113815,    2657637,      38964,    3225167,     622137,
         36910560,   30366036,   54045420,    2494530,      10084,
         28608710,   17332850,    4841000,    6545502,   23310715,
        200963599,   25666161,    1836713,    5347896,    5266535,
        216565318,      18233,          0,    4246439,    8776109,
          7044636,   32510453,  108116615,   37970874,   10269417,
          2832067,   19356544,  144373535,   12626950,      52823,
           182790,     100455,     202506,      33860,   34268528,
         16296364,    6944975,      97625,    7813215,    5703569,
          5454073,    2087946,     669823,   15442905,   58558270,
         51709098,   11062113,   47076781,   21803000,   42813238,
           581372,   17070135,    9321018,   58005463,   69625582,
          3500000,    8082366,     100209,    1394973,   11694719,
         83429615,    5942089,      11646,   44269594,   44385155,
          9770529,   66834405,  328239523,    3461734,   33580650,
           299882,   28515829,   96462106,   29161922,   17861030,
         14645468])

In [106]:
df.Population = df.Population.fillna(0).astype('int64')

In [114]:
df.Population_Labor_force_participation.unique()

array([48.9, 55.7, 41.2,  0. , 77.5, 61.3, 55.6, 65.5, 60.7, 66.5, 74.6,
       73.4, 59. , 65.2, 64.1, 53.6, 65.1, 70.9, 66.7, 71.8, 46.4, 70.8,
       64.7, 55.4, 66.4, 79.2, 57. , 60.5, 82.3, 76.1, 72. , 70.7, 62.6,
       68. , 68.8, 43.3, 69.4, 62.1, 51.2, 63.1, 60.6, 63.5, 62.2, 60.2,
       64.3, 59.1, 62. , 78.4, 63.6, 79.6, 57.6, 55.1, 52.9, 59.4, 68.3,
       60.8, 67.8, 51.8, 62.3, 61.5, 56.2, 67.2, 56.5, 75. , 49.3, 67.5,
       44.7, 43. , 64. , 49.6, 66. , 61.7, 39.3, 74.7, 73.5, 59.8, 78.5,
       61.4, 47. , 67.9, 76.3, 49.7, 61.6, 59.3, 86.1, 76.7, 69.8, 45.9,
       58.3, 43.1, 59.7, 54.4, 45.3, 78.1, 59.5, 83.8, 69.9, 80.4, 63.8,
       72.4, 52.6, 66.6, 47.2, 72.1, 77.6, 59.6, 56.7, 58.8, 86.8, 54.7,
       61.8, 83.7, 67.1, 65.9, 43.7, 55.9, 45.7, 54.9, 57.9, 70.5, 58.4,
       47.4, 56. , 63. , 57.5, 53.9, 48.4, 51.1, 44.1, 42. , 83.4, 67.3,
       60. , 46.1, 52.8, 64.5, 70.3, 54.2, 82.1, 62.8, 77.4, 38. , 83.1])

In [111]:
df.Population_Labor_force_participation = df.Population_Labor_force_participation.str.replace('[%]', '', regex=True).astype('float64')

In [113]:
df.Population_Labor_force_participation = df.Population_Labor_force_participation.fillna(0)

In [119]:
df.Taxrevenue.unique()

array([ 9.3, 18.6, 37.2,  0. ,  9.2, 16.5, 10.1, 20.9, 23. , 25.4, 13. ,
       14.8,  4.2,  8.8, 27.5, 14.7, 24. , 26.3, 10.8, 16. , 17. , 20.4,
       19.5, 20.2, 15. , 13.6, 11.8, 20.1, 17.1, 12.8,  8.6, 18.2,  9.4,
       14.4,  9. , 22. , 24.5, 14.9, 10.7, 32.4, 22.1, 12.5, 18.1,  6.1,
       28.6,  7.5, 24.2, 20.8, 10.2, 21.7, 11.5, 12.6, 26.2, 19.4, 10.6,
       10.3, 17.3, 23.3, 11.2,  7.4,  2. , 18.3, 23.1, 24.3, 26.8, 11.9,
       15.1, 11.7,  1.4, 18. , 12.9, 22.9, 15.3, 31.6, 16.9, 26.5, 12. ,
       11.6, 17.8, 19.1, 13.1, 25.2, 17.7, 16.8, 21.9,  5.4, 27.1, 20.7,
       29. , 15.6,  1.5, 23.9,  2.5, 21.3, 10. , 14.3, 14. , 17.4, 22.8,
       14.6, 11.4, 18.5, 25.5,  8.9, 16.3, 34.1, 18.7, 29.5, 14.2,  8. ,
        9.8, 25. , 22.3, 21.1, 17.9,  0.1,  9.6, 16.2])

In [116]:
df.Taxrevenue = df.Taxrevenue.str.replace('[%]', '', regex=True).astype('float64')

In [118]:
df.Taxrevenue = df.Taxrevenue.fillna(0)

In [124]:
df.Totaltaxrate.unique()

array([ 71.4,  36.6,  66.1,   0. ,  49.1,  43. , 106.3,  22.6,  47.4,
        51.4,  40.7,  33.8,  13.8,  33.4,  35.6,  53.3,  55.4,  31.1,
        48.9,  35.3,  83.7,  23.7,  25.1,   8. ,  28.3,  41.3,  41.2,
        50.1,  37.5,  23.1,  57.7,  24.5,  73.3,  63.5,  34. ,  59.2,
        71.2, 219.6,  54.3,  58.3,  20.5,  22.4,  46.1,  50.7,  23.8,
        37.9,  32.6,  48.8,  34.4,  44.4,  36.4,  79.4,  47.8,  37.7,
        32.1,  60.7,  47.1,  48.4,   9.9,  51.9,  35.2,  69.3,  45.5,
        30.6,  42.7,  39.1,  31.9,  49.7,  30.1,  44.7,  30.8,  26.1,
        25.3,  59.1,  35.1,  46.7,  28.6,  28.4,  37.2,  32.7,  13. ,
        29. ,  24.1,  38.1,  32.2,  13.6,  46.2,  21.6,  42.6,  20.4,
        38.3,  34.5,  38.7,  30.2,  54.5,  44. ,  65.9,  67. ,  22.2,
        55.1,  60.5,  25.7,  45.8,  36.1,  31.2,  20.7,  41.8,  34.6,
        60.6,  47.2,  34.8,  36.2,  27.4,  33.9,  76.6,  37.1,  35. ,
        36.8,  43.1,  40.8,  39.8,  11.3,  20. ,  33.2,  34.7,  37. ,
        19.3,  15.7,  44.8,  30.7,  21. ,  31. ,  32. ,  29.2,  31.4,
        47. ,  55.2,  45.4,  27.9,  67.3,  43.8,  29.5,  17.3,  48.2,
        27.5,  40.5,  42.3,  33.7,  45.2,  15.9,  31.6,   8.5,  37.6,
        26.6,  15.6])

In [121]:
df.Totaltaxrate = df.Totaltaxrate.str.replace('[%]', '', regex=True).astype('float64')

In [123]:
df.Totaltaxrate = df.Totaltaxrate.fillna(0)

In [128]:
df.Unemploymentrate.unique()

array([11.12, 12.33, 11.7 ,  0.  ,  6.89,  9.79, 16.99,  5.27,  4.67,
        5.51, 10.36,  0.71,  4.19, 10.33,  4.59,  5.59,  6.41,  2.23,
        2.34,  3.5 , 18.42, 18.19,  9.12,  4.34,  6.26,  1.43,  3.32,
       12.25,  0.68,  3.38,  5.56,  3.68,  1.89,  7.09,  4.32,  9.71,
        9.47, 11.85,  6.93,  1.64,  7.27,  1.93,  4.24,  4.91, 10.3 ,
        5.84,  3.97, 10.76,  4.11,  6.43,  5.14,  5.11,  2.08,  4.1 ,
        6.59,  8.43, 20.  ,  9.06, 14.4 ,  3.04,  4.33, 17.24,  2.46,
        4.3 ,  2.47, 13.78,  5.39,  3.4 ,  2.84,  5.36,  4.69, 11.38,
       12.82,  4.93,  3.86,  9.89,  8.  ,  2.29, 14.72,  2.64,  2.18,
        6.33,  0.63,  6.52,  6.23, 23.41,  2.81, 18.56,  6.35,  1.76,
        5.65,  6.14,  7.22,  3.47,  9.55,  6.67,  3.42,  5.47,  6.01,
       14.88,  9.02,  3.24,  1.58, 20.27,  1.41,  3.2 ,  4.07,  6.84,
        0.47,  8.1 ,  2.74,  3.35,  2.67,  4.45,  3.9 ,  4.81,  3.31,
        2.15,  0.09,  3.98,  1.03, 20.71, 18.88,  8.36,  5.93,  6.6 ,
       12.69,  4.43,  4.2 ,  0.58, 11.35, 28.18,  4.15, 12.24, 13.96,
       16.53,  7.33,  8.37, 11.02,  1.98,  0.75,  4.55,  2.04,  1.12,
        2.69, 16.02, 13.49,  3.91,  1.84,  8.88,  2.35,  3.85, 14.7 ,
        8.73,  5.92,  4.39,  8.8 ,  2.01, 12.91, 11.43,  4.95])

In [126]:
df.Unemploymentrate = df.Unemploymentrate.str.replace('[%]', '', regex=True).astype('float64')

In [127]:
df.Unemploymentrate = df.Unemploymentrate.fillna(0)

In [137]:
df.Urban_population.unique()

array([  9797273,   1747593,  31510100,     67873,  21061025,     23800,
        41339571,   1869848,  21844756,   5194416,   5616165,    323784,
         1467109,  60987417,     89431,   7482982,  11259082,    179039,
         5648149,    317538,   8033035,   1605144,   1616550,    337711,
         5256027,   6092349,   1541177,  13176900,    364029,   3924621,
        14741256,  30628482,   1982064,   3712273,  16610135, 842933962,
        40827302,    248152,   3625010,   4041885,   2328318,   8739135,
          800708,   7887156,  39095679,   5119978,    758549,     50830,
         8787475,  11116711,  42895824,   4694702,    984812,   1149670,
          916024,         0,  23788710,    505048,   4716888,  54123364,
         1949694,   1453958,   2196476,  64324835,  17249054,   8507474,
           40765,   8540945,   4661505,    840922,    208912,   6328948,
         5626433,   6999582,    339110, 471031528, 151509724,  62509623,
        27783368,   3133123,   8374393,  42651966,   1650594, 115782416,
         9213048,  10652915,  14461523,     64489,   4207083,   2362644,
         2555552,   1304943,   6084994,    607508,   2548426,   5448597,
            5464,   1891013,    565488,  10210849,   3199301,  24475766,
          213645,   8479688,    475902,     45514,   2466821,    515980,
       102626859,     25963,   1135502,     38964,   2210626,    417765,
        22975026,  11092106,  16674093,   1273258,   5765513,  15924729,
         4258860,   3846137,   3850231, 102806948,  15947412,   4418218,
         4250777,  79927762,     14491,   2890084,   1162834,   4359150,
        25390339,  50975903,  22796574,   6753579,   2809071,  10468793,
       107683889,   2186104,     16269,     34280,     58185,     35588,
           32969,  28807838,   7765706,   3907243,     55762,   3319366,
         5703569,   2930419,   1144654,    162164,   7034861,  39149717,
        42106719,   2201250,  37927409,   4052088,  14957233,    384258,
         9358019,   2545477,  20011885,  35294600,    400182,   3414638,
           24145,    741944,   8099061,  63097818,   3092738,      7362,
        10784516,  30835699,   8479744,  55908316, 270663028,   3303394,
        16935729,     76152,  25162368,  35332140,  10869523,   7871713,
         4717305])

In [139]:
df.Urban_population = df.Urban_population.str.replace('[,]', '', regex=True)

AttributeError: Can only use .str accessor with string values!

In [136]:
df.Urban_population = df.Urban_population.fillna(0).astype('int64')

In [140]:
df.Latitude.unique()

array([ 3.39391100e+01,  4.11533320e+01,  2.80338860e+01,  4.25062850e+01,
       -1.12026920e+01,  1.70608160e+01, -3.84160970e+01,  4.00690990e+01,
       -2.52743980e+01,  4.75162310e+01,  4.01431050e+01,  2.50342800e+01,
        2.60667000e+01,  2.36849940e+01,  1.31938870e+01,  5.37098070e+01,
        5.05038870e+01,  1.71898770e+01,  9.30769000e+00,  2.75141620e+01,
       -1.62901540e+01,  4.39158860e+01, -2.23284740e+01,  4.53527700e+00,
        4.27338830e+01,  1.22383330e+01, -3.37305600e+00,  7.53998900e+00,
        1.65388000e+01,  1.25656790e+01,  7.36972200e+00,  5.61303660e+01,
        6.61111100e+00,  1.54541660e+01, -3.56751470e+01,  3.58616600e+01,
        4.57086800e+00, -1.16455000e+01, -2.28021000e-01,  9.74891700e+00,
        4.51000000e+01,  2.15217570e+01,  3.51264130e+01,  4.98174920e+01,
       -4.03833300e+00,  5.62639200e+01,  1.18251380e+01,  1.54149990e+01,
        1.87356930e+01, -1.83123900e+00,  2.68205530e+01,  1.37941850e+01,
        1.65080100e+00,  1.51793840e+01,  5.85952720e+01, -2.65225030e+01,
        9.14500000e+00, -1.77133710e+01,  6.19241100e+01,  4.62276380e+01,
       -8.03689000e-01,  1.34431820e+01,  4.23154070e+01,  5.11656910e+01,
        7.94652700e+00,  3.90742080e+01,  1.21165000e+01,  1.57834710e+01,
        9.94558700e+00,  1.18037490e+01,  4.86041600e+00,  1.89711870e+01,
        4.19029160e+01,  1.51999990e+01,  4.71624940e+01,  6.49630510e+01,
        2.05936840e+01, -7.89275000e-01,  3.24279080e+01,  3.32231910e+01,
        5.34129100e+01,  3.10460510e+01,  4.18719400e+01,  1.81095810e+01,
        3.62048240e+01,  3.05851640e+01,  4.80195730e+01, -2.35590000e-02,
        1.83689760e+00,  2.93116600e+01,  4.12043800e+01,  1.98562700e+01,
        5.68796350e+01,  3.38547210e+01, -2.96099880e+01,  6.42805500e+00,
        2.63351000e+01,  4.71410392e+01,  5.51694380e+01,  4.98152730e+01,
       -1.87669470e+01, -1.32543080e+01,  4.21048400e+00,  3.20277800e+00,
        1.75706920e+01,  3.59374960e+01,  7.13147400e+00,  2.10078900e+01,
       -2.03484040e+01,  2.36345010e+01,  7.42555400e+00,  4.74116310e+01,
        4.37384176e+01,  4.68624960e+01,  4.27086780e+01,  3.17917020e+01,
       -1.86656950e+01,  2.19162210e+01, -2.29576400e+01, -5.22778000e-01,
        2.83948570e+01,  5.21326330e+01, -4.09005570e+01,  1.28654160e+01,
        1.76077890e+01,  9.08199900e+00,  4.03398520e+01,  4.16086350e+01,
        6.04720240e+01,  2.14735329e+01,  3.03753210e+01,  7.51498000e+00,
        3.19521620e+01,  8.53798100e+00, -6.31499300e+00, -2.34425030e+01,
       -9.18996700e+00,  1.28797210e+01,  5.19194380e+01,  3.93998720e+01,
        2.53548260e+01,  4.59431610e+01,  6.15240100e+01, -1.94027800e+00,
        1.73578220e+01,  1.39094440e+01,  1.29843050e+01, -1.37590290e+01,
        4.39423600e+01,  2.38859420e+01,  1.44974010e+01,  4.40165210e+01,
       -4.67957400e+00,  8.46055500e+00,  1.35208300e+00,  4.86690260e+01,
        4.61512410e+01, -9.64571000e+00,  5.15214900e+00, -3.05594820e+01,
        3.59077570e+01,  6.87699190e+00,  4.04636670e+01,  7.87305400e+00,
        1.28628070e+01,  3.91930500e+00,  3.48020750e+01,  3.88610340e+01,
       -6.36902800e+00,  1.58700320e+01, -8.87421700e+00,  8.61954300e+00,
       -2.11789860e+01,  1.06918030e+01,  3.38869170e+01,  3.89637450e+01,
        3.89697190e+01, -7.10953500e+00,  1.37333300e+00,  4.83794330e+01,
        2.34240760e+01,  5.53780510e+01,  3.70902400e+01, -3.25227790e+01,
        4.13774910e+01, -1.53767060e+01,  6.42375000e+00,  1.40583240e+01,
        1.55527270e+01, -1.31338970e+01, -1.90154380e+01])

In [180]:
df = df.drop('Longitude',axis=1)

In [181]:
df

,Country,Density,Abbreviation,Agricultural_Land,Land_Area,ArmedForcessize,BirthRate,Capital_MajorCity,Co2_Emissions,CPI,...,Officiallanguage,Outofpockethealthexpenditure,Physiciansperthousand,Population,Population_Labor_force_participation,Taxrevenue,Totaltaxrate,Unemploymentrate,Urban_population,Latitude
0,Afghanistan,60,AF,58.1,652230,323000,32.49,Kabul,8672,149.90,...,Pashto,78.4,0.28,38041754,48.9,9.3,71.4,11.12,9797273,33.939110
1,Albania,105,AL,43.1,28748,9000,11.78,Tirana,4536,119.05,...,Albanian,56.9,1.20,2854191,55.7,18.6,36.6,12.33,1747593,41.153332
2,Algeria,18,DZ,17.4,2381741,317000,24.28,Algiers,150006,151.36,...,Arabic,28.1,1.72,43053054,41.2,37.2,66.1,11.70,31510100,28.033886
3,Andorra,164,AD,40.0,468,0,7.20,Andorra la Vella,469,0.00,...,Catalan,36.4,3.33,77142,0.0,0.0,0.0,0.00,67873,42.506285
4,Angola,26,AO,47.5,1246700,117000,40.73,Luanda,34693,261.73,...,Portuguese,33.4,0.21,31825295,77.5,9.2,49.1,6.89,21061025,-11.202692
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.5,912050,343000,17.88,Caracas,164175,2740.27,...,Spanish,45.8,1.92,28515829,59.7,0.0,73.3,8.80,25162368,6.423750
191,Vietnam,314,VN,39.3,331210,522000,16.75,Hanoi,192668,163.52,...,Vietnamese,43.5,0.82,96462106,77.4,19.1,37.6,2.01,35332140,14.058324
192,Yemen,56,YE,44.6,527968,40000,30.45,Sanaa,10609,157.58,...,Arabic,81.0,0.31,29161922,38.0,0.0,26.6,12.91,10869523,15.552727
193,Zambia,25,ZM,32.1,752618,16000,36.19,Lusaka,5141,212.31,...,English,27.5,1.19,17861030,74.6,16.2,15.6,11.43,7871713,-13.133897
194,Zimbabwe,38,ZW,41.9,390757,51000,30.68,Harare,10983,105.51,...,Shona,25.8,0.21,14645468,83.1,20.7,31.6,4.95,4717305,-19.015438

In [141]:
df.Longitude.isnull().sum()

np.int64(0)

In [142]:
df.Latitude.unique()

array([ 3.39391100e+01,  4.11533320e+01,  2.80338860e+01,  4.25062850e+01,
       -1.12026920e+01,  1.70608160e+01, -3.84160970e+01,  4.00690990e+01,
       -2.52743980e+01,  4.75162310e+01,  4.01431050e+01,  2.50342800e+01,
        2.60667000e+01,  2.36849940e+01,  1.31938870e+01,  5.37098070e+01,
        5.05038870e+01,  1.71898770e+01,  9.30769000e+00,  2.75141620e+01,
       -1.62901540e+01,  4.39158860e+01, -2.23284740e+01,  4.53527700e+00,
        4.27338830e+01,  1.22383330e+01, -3.37305600e+00,  7.53998900e+00,
        1.65388000e+01,  1.25656790e+01,  7.36972200e+00,  5.61303660e+01,
        6.61111100e+00,  1.54541660e+01, -3.56751470e+01,  3.58616600e+01,
        4.57086800e+00, -1.16455000e+01, -2.28021000e-01,  9.74891700e+00,
        4.51000000e+01,  2.15217570e+01,  3.51264130e+01,  4.98174920e+01,
       -4.03833300e+00,  5.62639200e+01,  1.18251380e+01,  1.54149990e+01,
        1.87356930e+01, -1.83123900e+00,  2.68205530e+01,  1.37941850e+01,
        1.65080100e+00,  1.51793840e+01,  5.85952720e+01, -2.65225030e+01,
        9.14500000e+00, -1.77133710e+01,  6.19241100e+01,  4.62276380e+01,
       -8.03689000e-01,  1.34431820e+01,  4.23154070e+01,  5.11656910e+01,
        7.94652700e+00,  3.90742080e+01,  1.21165000e+01,  1.57834710e+01,
        9.94558700e+00,  1.18037490e+01,  4.86041600e+00,  1.89711870e+01,
        4.19029160e+01,  1.51999990e+01,  4.71624940e+01,  6.49630510e+01,
        2.05936840e+01, -7.89275000e-01,  3.24279080e+01,  3.32231910e+01,
        5.34129100e+01,  3.10460510e+01,  4.18719400e+01,  1.81095810e+01,
        3.62048240e+01,  3.05851640e+01,  4.80195730e+01, -2.35590000e-02,
        1.83689760e+00,  2.93116600e+01,  4.12043800e+01,  1.98562700e+01,
        5.68796350e+01,  3.38547210e+01, -2.96099880e+01,  6.42805500e+00,
        2.63351000e+01,  4.71410392e+01,  5.51694380e+01,  4.98152730e+01,
       -1.87669470e+01, -1.32543080e+01,  4.21048400e+00,  3.20277800e+00,
        1.75706920e+01,  3.59374960e+01,  7.13147400e+00,  2.10078900e+01,
       -2.03484040e+01,  2.36345010e+01,  7.42555400e+00,  4.74116310e+01,
        4.37384176e+01,  4.68624960e+01,  4.27086780e+01,  3.17917020e+01,
       -1.86656950e+01,  2.19162210e+01, -2.29576400e+01, -5.22778000e-01,
        2.83948570e+01,  5.21326330e+01, -4.09005570e+01,  1.28654160e+01,
        1.76077890e+01,  9.08199900e+00,  4.03398520e+01,  4.16086350e+01,
        6.04720240e+01,  2.14735329e+01,  3.03753210e+01,  7.51498000e+00,
        3.19521620e+01,  8.53798100e+00, -6.31499300e+00, -2.34425030e+01,
       -9.18996700e+00,  1.28797210e+01,  5.19194380e+01,  3.93998720e+01,
        2.53548260e+01,  4.59431610e+01,  6.15240100e+01, -1.94027800e+00,
        1.73578220e+01,  1.39094440e+01,  1.29843050e+01, -1.37590290e+01,
        4.39423600e+01,  2.38859420e+01,  1.44974010e+01,  4.40165210e+01,
       -4.67957400e+00,  8.46055500e+00,  1.35208300e+00,  4.86690260e+01,
        4.61512410e+01, -9.64571000e+00,  5.15214900e+00, -3.05594820e+01,
        3.59077570e+01,  6.87699190e+00,  4.04636670e+01,  7.87305400e+00,
        1.28628070e+01,  3.91930500e+00,  3.48020750e+01,  3.88610340e+01,
       -6.36902800e+00,  1.58700320e+01, -8.87421700e+00,  8.61954300e+00,
       -2.11789860e+01,  1.06918030e+01,  3.38869170e+01,  3.89637450e+01,
        3.89697190e+01, -7.10953500e+00,  1.37333300e+00,  4.83794330e+01,
        2.34240760e+01,  5.53780510e+01,  3.70902400e+01, -3.25227790e+01,
        4.13774910e+01, -1.53767060e+01,  6.42375000e+00,  1.40583240e+01,
        1.55527270e+01, -1.31338970e+01, -1.90154380e+01])

In [182]:
df = df.drop('Latitude',axis=1)

In [183]:
df

,Country,Density,Abbreviation,Agricultural_Land,Land_Area,ArmedForcessize,BirthRate,Capital_MajorCity,Co2_Emissions,CPI,...,Minimumwage,Officiallanguage,Outofpockethealthexpenditure,Physiciansperthousand,Population,Population_Labor_force_participation,Taxrevenue,Totaltaxrate,Unemploymentrate,Urban_population
0,Afghanistan,60,AF,58.1,652230,323000,32.49,Kabul,8672,149.90,...,0.43,Pashto,78.4,0.28,38041754,48.9,9.3,71.4,11.12,9797273
1,Albania,105,AL,43.1,28748,9000,11.78,Tirana,4536,119.05,...,1.12,Albanian,56.9,1.20,2854191,55.7,18.6,36.6,12.33,1747593
2,Algeria,18,DZ,17.4,2381741,317000,24.28,Algiers,150006,151.36,...,0.95,Arabic,28.1,1.72,43053054,41.2,37.2,66.1,11.70,31510100
3,Andorra,164,AD,40.0,468,0,7.20,Andorra la Vella,469,0.00,...,6.63,Catalan,36.4,3.33,77142,0.0,0.0,0.0,0.00,67873
4,Angola,26,AO,47.5,1246700,117000,40.73,Luanda,34693,261.73,...,0.71,Portuguese,33.4,0.21,31825295,77.5,9.2,49.1,6.89,21061025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.5,912050,343000,17.88,Caracas,164175,2740.27,...,0.01,Spanish,45.8,1.92,28515829,59.7,0.0,73.3,8.80,25162368
191,Vietnam,314,VN,39.3,331210,522000,16.75,Hanoi,192668,163.52,...,0.73,Vietnamese,43.5,0.82,96462106,77.4,19.1,37.6,2.01,35332140
192,Yemen,56,YE,44.6,527968,40000,30.45,Sanaa,10609,157.58,...,0.00,Arabic,81.0,0.31,29161922,38.0,0.0,26.6,12.91,10869523
193,Zambia,25,ZM,32.1,752618,16000,36.19,Lusaka,5141,212.31,...,0.24,English,27.5,1.19,17861030,74.6,16.2,15.6,11.43,7871713
194,Zimbabwe,38,ZW,41.9,390757,51000,30.68,Harare,10983,105.51,...,0.00,Shona,25.8,0.21,14645468,83.1,20.7,31.6,4.95,4717305

In [143]:
df.Latitude.isnull().sum()

np.int64(0)

In [185]:
df.dtypes

Country                                  object
Density                                   int64
Abbreviation                             object
Agricultural_Land                       float64
Land_Area                                 int64
ArmedForcessize                           int64
BirthRate                               float64
Capital_MajorCity                        object
Co2_Emissions                             int64
CPI                                     float64
CPIChange                               float64
FertilityRate                           float64
ForestedArea                            float64
GasolinePrice                           float64
GDP                                       int64
Grossprimaryeducationenrollment         float64
Grosstertiaryeducationenrollment        float64
Infantmortality                         float64
Largestcity                              object
Lifeexpectancy                          float64
Maternalmortalityratio                  float64
Minimumwage                             float64
Officiallanguage                         object
Outofpockethealthexpenditure            float64
Physiciansperthousand                   float64
Population                                int64
Population_Labor_force_participation    float64
Taxrevenue                              float64
Totaltaxrate                            float64
Unemploymentrate                        float64
Urban_population                          int64
dtype: object

In [184]:
df.columns

Index(['Country', 'Density', 'Abbreviation', 'Agricultural_Land', 'Land_Area',
       'ArmedForcessize', 'BirthRate', 'Capital_MajorCity', 'Co2_Emissions',
       'CPI', 'CPIChange', 'FertilityRate', 'ForestedArea', 'GasolinePrice',
       'GDP', 'Grossprimaryeducationenrollment',
       'Grosstertiaryeducationenrollment', 'Infantmortality', 'Largestcity',
       'Lifeexpectancy', 'Maternalmortalityratio', 'Minimumwage',
       'Officiallanguage', 'Outofpockethealthexpenditure',
       'Physiciansperthousand', 'Population',
       'Population_Labor_force_participation', 'Taxrevenue', 'Totaltaxrate',
       'Unemploymentrate', 'Urban_population'],
      dtype='object')

In [186]:
df.to_csv('Global_World_Data.csv')